import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { cardRecordToDefinition } from '../cards/published-cards';
import { generateCardInstance } from '../cards/generation';
import { createInitialGameState } from './create-initial-game-state';
import { executeAction } from '../actions/engine-actions';
import type { CardDefinition, CardInstance } from '../cards/types';
import type { GameState } from '../types/game-state';
const records=JSON.parse(readFileSync(new URL('../qa/fixtures/card-audit-2026-10-05.json',import.meta.url),'utf8')).cards;
const defs:CardDefinition[]=records.map(cardRecordToDefinition);
const definition=(name:string)=>defs.find(c=>c.name===name)!;
const unit:CardDefinition={id:'audit-unit',name:'검사 선수',cardType:'WRESTLER',cost:1,attack:2,health:10,rulesText:'',isToken:false,isChampionToken:false,keywords:[],abilities:[]};
function setup(){const s=createInitialGameState();s.status='IN_PROGRESS';s.turn=3;s.activePlayerId='player-1';s.cardPool=[...defs,unit];for(const p of s.players){p.hand=[];p.deck=[];p.board=[null,null,null,null];p.graveyard=[];p.mulliganUsed=true;p.currentGold=100;}return s;}
const card=(id:string,extra:Partial<CardInstance>={})=>({...generateCardInstance(unit,{instanceId:id}),...extra});
function play(s:GameState,name:string,targets:string[]=[]){const d=definition(name);s.players[0].hand.unshift(generateCardInstance(d,{instanceId:'source'}));let r=executeAction(s,d.cardType==='TECHNIQUE'?{type:'PLAY_TECHNIQUE',playerId:'player-1',cardInstanceId:'source'}:{type:'PLAY_WRESTLER',playerId:'player-1',cardInstanceId:'source',boardSlot:0});assert.ok(r.success);for(const targetId of targets){r=executeAction(r.state,{type:'SELECT_EFFECT_TARGET',playerId:'player-1',targetId});assert.ok(r.success);}return r.state;}
test('Ozen includes cost equal to one, excludes champions, and destroys without retirement',()=>{
  for(const cost of [0,1,2]){const s=setup();s.players[1].board[0]=card('victim',{boardSlot:0,currentCost:cost});const result=play(s,'오젠');assert.equal(result.players[1].board[0]===null,cost<=1);assert.equal(result.players[1].graveyard.length,0);assert.equal(result.events.some(e=>e.type==='CARD_RETIRED'),false);assert.equal(result.events.some(e=>e.type==='CARD_DESTROYED'),cost<=1);}
  const s=setup();s.cardPool!.push({...unit,id:'champion-unit',rarity:'CHAMPION'});s.players[1].board[0]=card('champion',{definitionId:'champion-unit',boardSlot:0,currentCost:1});assert.ok(play(s,'오젠').players[1].board[0]);
});
test('Baldan destroys one graveyard card then summons a base zombie without copying unrelated stats',()=>{const s=setup();s.players[0].graveyard=[card('grave',{currentAttack:99,currentHealth:99,maxHealth:99})];const n=play(s,'발단');assert.equal(n.players[0].graveyard.length,0);const zombie=n.players[0].board.find(c=>c?.definitionId===definition('좀비').id)!;assert.deepEqual([zombie.currentAttack,zombie.currentHealth],[1,1]);assert.ok(n.events.some(e=>e.type==='CARD_DESTROYED'&&e.cardInstanceId==='grave'));assert.equal(n.events.some(e=>e.type==='CARD_RETIRED'),false);});
test('Life Exchange swaps wounded current and maximum health before either target changes',()=>{for(const reverse of [false,true]){const s=setup();s.players[0].board[1]=card('ally',{boardSlot:1,currentHealth:reverse?7:2,maxHealth:reverse?10:3,currentAttack:4});s.players[1].board[0]=card('enemy',{boardSlot:0,currentHealth:reverse?2:7,maxHealth:reverse?3:10,currentAttack:6});const n=play(s,'생명의 교환',['ally','enemy']);assert.deepEqual([n.players[0].board[1]!.currentHealth,n.players[0].board[1]!.maxHealth],reverse?[2,3]:[7,10]);assert.deepEqual([n.players[1].board[0]!.currentHealth,n.players[1].board[0]!.maxHealth],reverse?[7,10]:[2,3]);assert.equal(n.players[0].board[1]!.currentAttack,4);assert.equal(n.players[1].board[0]!.currentAttack,6);assert.ok(n.players[0].board[1]!.isStunned&&n.players[1].board[0]!.isStunned);assert.equal(n.players[0].board[1]!.baseHealth,10);}});
test('Question includes costs zero and one across all playable zones, excludes two',()=>{const s=setup();s.players[0].hand=[0,1,2].map(cost=>card('hand'+cost,{currentCost:cost}));s.players[0].deck=[0,1,2].map(cost=>card('deck'+cost,{currentCost:cost}));s.players[0].board[1]=card('board1',{boardSlot:1,currentCost:1});const n=play(s,'퀘스쳔');for(const c of [...n.players[0].hand,...n.players[0].deck,n.players[0].board[1]!])assert.deepEqual([c.currentAttack,c.currentHealth],c.currentCost<=1?[3,11]:[2,10]);});
test('Calavera includes cost three while Gilded includes cost six',()=>{let s=setup();s.players[0].graveyard=[card('three',{currentCost:3}),card('four',{currentCost:4})];let n=play(s,'라 칼라베라');assert.ok(n.players[0].board.some(c=>c?.instanceId==='three'));assert.ok(n.players[0].graveyard.some(c=>c.instanceId==='four'));s=setup();s.players[0].hand=[5,6,7].map(cost=>card('cost'+cost,{currentCost:cost}));n=play(s,'도금구슬 마스터');assert.deepEqual(n.players[0].hand.map(c=>c.currentCost),[5,5,6]);});
test('Joker can generate a spell and floors all generated stats at one',()=>{const s=setup();s.cardPool=[{...unit,id:'zero-spell',name:'검사 주문',cardType:'TECHNIQUE',cost:0,attack:0,health:0}];s.players[0].deck=[card('deck-top')];const n=play(s,'아르카나 조커');const c=n.players[0].deck[0];assert.equal(c.definitionId,'zero-spell');assert.deepEqual([c.currentCost,c.currentAttack,c.currentHealth,c.maxHealth],[1,1,1,1]);assert.equal(n.players[0].graveyard.length,0);});
test('a technique cannot be played as a wrestler to bypass casting',()=>{const s=setup();s.players[0].hand=[generateCardInstance(definition('생명의 교환'),{instanceId:'spell'})];const r=executeAction(s,{type:'PLAY_WRESTLER',playerId:'player-1',cardInstanceId:'spell',boardSlot:0});assert.equal(r.success,false);assert.deepEqual(r.state,s);});
