import test from 'node:test';
import assert from 'node:assert/strict';
import { EPIC_TECHNIQUES } from '../cards/epic-techniques';
import { cardRecordToDefinition } from '../cards/published-cards';
import { isEffectScript } from '@workspace/effect-registry';
import { generateCardInstance } from '../cards/generation';
import { createInitialGameState } from './create-initial-game-state';
import { executeAction, getLegalActions } from '../actions/engine-actions';
import { endTurn } from './turn-system';
import type { CardDefinition } from '../cards/types';
const unit: CardDefinition = {id:'unit',name:'선수',cardType:'WRESTLER',cost:7,attack:2,health:10,rulesText:'',isToken:false,isChampionToken:false,keywords:[],abilities:[]};
function setup(id:string) {
 const spell=cardRecordToDefinition(EPIC_TECHNIQUES.find(c=>c.id==='epic-spell-'+id)!);
 const s=createInitialGameState();s.status='IN_PROGRESS';s.activePlayerId='player-1';s.turn=3;s.cardPool=[unit,...EPIC_TECHNIQUES.map(cardRecordToDefinition)];s.players[0].currentGold=10;
 s.players[0].hand=[generateCardInstance(spell,{instanceId:'spell'})];
 s.players[0].board[0]={...generateCardInstance(unit,{instanceId:'ally'}),boardSlot:0,currentHealth:2};
 s.players[1].board[0]={...generateCardInstance(unit,{instanceId:'enemy'}),boardSlot:0,currentHealth:7,currentAttack:6};
 return s;
}
function play(s:ReturnType<typeof setup>,targets:string[]=[]) {
 let r=executeAction(s,{type:'PLAY_TECHNIQUE',playerId:'player-1',cardInstanceId:'spell'});assert.ok(r.success,JSON.stringify(r.error));
 for(const targetId of targets){assert.ok(r.state.targetingState?.validTargetIds.includes(targetId));r=executeAction(r.state,{type:'SELECT_EFFECT_TARGET',playerId:'player-1',targetId});assert.ok(r.success);}
 return r.state;
}
test('11 catalog entries serialize as EPIC techniques with active effects and no combat stats',()=>{
 assert.equal(EPIC_TECHNIQUES.length,11);assert.equal(new Set(EPIC_TECHNIQUES.map(c=>c.id)).size,11);
 for(const c of EPIC_TECHNIQUES){const d=cardRecordToDefinition(JSON.parse(JSON.stringify(c)));assert.equal(d.rarity,'EPIC');assert.equal(d.cardType,'TECHNIQUE');assert.equal(d.attack,0);assert.equal(d.health,0);assert.equal(d.abilities.length,1);if(c.effectId==='SCRIPT_V1')assert.ok((c.effectConfig.scripts as unknown[]).every(isEffectScript));}
});
test('처형 destroys enemy without graveyard or retire effects',()=>{const s=setup('execution');s.players[1].board[0]!.abilities=[{trigger:'SELF_RETIRE',effects:[{type:'STRUCTURED',action:'ADD_GOLD',values:{amount:99}}]}];const a=play(s,['enemy']);assert.equal(a.players[1].board[0],null);assert.equal(a.players[1].graveyard.length,0);assert.equal(a.players[1].currentGold,s.players[1].currentGold);});
test('만찬 permanently adds current and maximum HP to every ally only',()=>{const s=setup('feast');s.players[0].board[1]={...s.players[0].board[0]!,instanceId:'ally2',boardSlot:1};const a=play(s);for(const c of a.players[0].board.filter(Boolean)){assert.equal(c!.currentHealth,5);assert.equal(c!.maxHealth,13);}assert.equal(a.players[1].board[0]!.currentHealth,7);});
test('침묵의 장막 silences every enemy, including already silenced, preserving allies',()=>{const s=setup('veil-of-silence');s.players[1].board[1]={...s.players[1].board[0]!,instanceId:'enemy2',boardSlot:1,isSilenced:true};const a=play(s);assert.ok(a.players[1].board.filter(Boolean).every(c=>c!.isSilenced));assert.equal(a.players[0].board[0]!.isSilenced,false);});
for(const n of [1,2,3,5]) test(`복귀 samples at most 3 of ${n}, moves only choice and resets`,()=>{
 const s=setup('return');s.players[0].graveyard=Array.from({length:n},(_,i)=>({...generateCardInstance(unit,{instanceId:'grave'+i}),currentAttack:99,currentHealth:1,maxHealth:99,currentCost:0,isSilenced:true,isStunned:true}));
 const a=play(s);const ids=a.targetingState!.validTargetIds;assert.equal(ids.length,Math.min(n,3));const r=executeAction(a,{type:'SELECT_EFFECT_TARGET',playerId:'player-1',targetId:ids[0]});assert.ok(r.success);assert.equal(r.state.targetingState,undefined);assert.equal(r.state.players[0].graveyard.filter(c=>c.cardType==='WRESTLER').length,n-1);const c=r.state.players[0].deck.find(c=>c.instanceId===ids[0])!;assert.equal(c.currentAttack,2);assert.equal(c.currentHealth,10);assert.equal(c.maxHealth,10);assert.equal(c.currentCost,7);assert.equal(c.isSilenced,false);assert.equal(c.isStunned,false);
 if(n>3){const excluded=s.players[0].graveyard.find(c=>!ids.includes(c.instanceId))!;assert.equal(executeAction(a,{type:'SELECT_EFFECT_TARGET',playerId:'player-1',targetId:excluded.instanceId}).success,false);}
});
test('금지된 계약 deals 5 and reserves one free wrestler only during this turn',()=>{
 const s=setup('forbidden-contract');const before=s.players[0].health;let a=play(s);assert.equal(a.players[0].health,before-5);assert.equal(a.pendingCardEffects!.length,1);
 a.players[0].currentGold=0;a.players[0].hand=[generateCardInstance(unit,{instanceId:'free'})];let r=executeAction(a,{type:'PLAY_WRESTLER',playerId:'player-1',cardInstanceId:'free',boardSlot:1});assert.ok(r.success);assert.equal(r.state.players[0].currentGold,0);assert.equal(r.state.pendingCardEffects!.length,0);r.state.players[0].hand=[generateCardInstance(unit,{instanceId:'paid'})];assert.equal(executeAction(r.state,{type:'PLAY_WRESTLER',playerId:'player-1',cardInstanceId:'paid',boardSlot:2}).success,false);
 a=play(setup('forbidden-contract'));const expire=endTurn(a,'player-1');assert.ok(expire.success);assert.equal(expire.state.pendingCardEffects!.length,0);
 a=play(setup('forbidden-contract'));a.players[0].hand=[generateCardInstance(cardRecordToDefinition(EPIC_TECHNIQUES.find(c=>c.name==='만찬')!),{instanceId:'spell2'})];a.players[0].currentGold=0;assert.equal(executeAction(a,{type:'PLAY_TECHNIQUE',playerId:'player-1',cardInstanceId:'spell2'}).success,false);assert.equal(a.pendingCardEffects!.length,1);
});
for(const [id,stat] of [['life-exchange','currentHealth'],['forced-exchange','currentAttack']] as const)test(`${id} selects both factions, snapshots and swaps ${stat}, stuns both`,()=>{const s=setup(id);const ally=s.players[0].board[0]![stat],enemy=s.players[1].board[0]![stat];let a=play(s);assert.deepEqual(a.targetingState!.validTargetIds,['ally']);assert.equal(executeAction(a,{type:'SELECT_EFFECT_TARGET',playerId:'player-1',targetId:'enemy'}).success,false);let r=executeAction(a,{type:'SELECT_EFFECT_TARGET',playerId:'player-1',targetId:'ally'});assert.ok(r.success);assert.deepEqual(r.state.targetingState!.validTargetIds,['enemy']);r=executeAction(r.state,{type:'SELECT_EFFECT_TARGET',playerId:'player-1',targetId:'enemy'});assert.ok(r.success);a=r.state;assert.equal(a.players[0].board[0]![stat],enemy);assert.equal(a.players[1].board[0]![stat],ally);assert.equal(a.players[0].board[0]!.maxHealth,10);assert.ok(a.players[0].board[0]!.isStunned);assert.ok(a.players[1].board[0]!.isStunned);assert.equal(unit.attack,2);});
test('생명의 교환 swaps current and maximum HP independently without clamping to old maxima',()=>{const s=setup('life-exchange');s.players[0].board[0]!.maxHealth=3;const a=play(s,['ally','enemy']);assert.deepEqual([a.players[0].board[0]!.currentHealth,a.players[0].board[0]!.maxHealth],[7,10]);assert.deepEqual([a.players[1].board[0]!.currentHealth,a.players[1].board[0]!.maxHealth],[2,3]);assert.equal(a.players[0].board[0]!.currentAttack,2);assert.equal(a.players[1].board[0]!.currentAttack,6);assert.ok(a.players[0].board[0]!.isStunned&&a.players[1].board[0]!.isStunned);});
test('절멸 snapshots current ATK <=3 on both sides, no retire',()=>{const s=setup('annihilation');s.players[1].board[1]={...s.players[1].board[0]!,instanceId:'weak',boardSlot:1,currentAttack:3,abilities:[{trigger:'SELF_RETIRE',effects:[{type:'STRUCTURED',action:'ADD_GOLD',values:{amount:99}}]}]};const a=play(s);assert.equal(a.players[0].board[0],null);assert.equal(a.players[1].board[1],null);assert.ok(a.players[1].board[0]);assert.equal(a.players[1].graveyard.length,0);assert.equal(a.players[0].graveyard.filter(c=>c.cardType==='WRESTLER').length,0);});
test('탈출 resets original stats/cost/status without retire and does not affect enemy',()=>{const s=setup('escape');Object.assign(s.players[0].board[0]!,{currentAttack:99,maxHealth:99,currentCost:0,isSilenced:true,isStunned:true});const a=play(s,['ally']);const c=a.players[0].hand[0];assert.equal(a.players[0].board[0],null);assert.equal(c.currentAttack,2);assert.equal(c.currentHealth,10);assert.equal(c.currentCost,7);assert.equal(c.isSilenced,false);assert.equal(c.isStunned,false);assert.equal(a.players[0].graveyard.filter(c=>c.cardType==='WRESTLER').length,0);assert.ok(a.players[1].board[0]);});
test('강제 침묵 accepts an already silenced enemy and resets original specs',()=>{const s=setup('forced-silence');Object.assign(s.players[1].board[0]!,{isSilenced:true,currentAttack:99,maxHealth:99});const a=play(s,['enemy']);assert.equal(a.players[1].board[0]!.isSilenced,true);assert.equal(a.players[1].board[0]!.currentAttack,2);assert.equal(a.players[1].board[0]!.maxHealth,10);});
test('밀쳐내기 uses existing stun flag and owner-turn expiry',()=>{const a=play(setup('push'),['enemy']);assert.ok(a.players[1].board[0]!.isStunned);const r=endTurn(a,'player-1');assert.ok(r.success);assert.equal(r.state.players[1].board[0]!.isStunned,true);const next=endTurn(r.state,'player-2');assert.ok(next.success);assert.equal(next.state.players[1].board[0]!.isStunned,false);});
for(const id of ['execution','return','life-exchange','forced-exchange','escape','forced-silence','push'])test(`${id} no target rejects before payment and AI has no illegal cast`,()=>{const s=setup(id);s.players[0].board=[null,null,null,null];s.players[1].board=[null,null,null,null];const r=executeAction(s,{type:'PLAY_TECHNIQUE',playerId:'player-1',cardInstanceId:'spell'});assert.equal(r.success,false);assert.deepEqual(r.state,s);assert.ok(!getLegalActions(s,'player-1').some(a=>a.type==='PLAY_TECHNIQUE'));});
for(const id of ['life-exchange','forced-exchange'])test(`${id} missing either faction cannot start a selection`,()=>{for(const side of [0,1]){const s=setup(id);s.players[side].board=[null,null,null,null];assert.equal(executeAction(s,{type:'BEGIN_TARGETED_ACTION',playerId:'player-1',action:{type:'PLAY_TECHNIQUE',cardInstanceId:'spell'}}).success,false);}});
test('복귀 includes token wrestlers and graveyard immunity is not a field state',()=>{const s=setup('return');s.players[0].graveyard=[{...generateCardInstance(unit,{instanceId:'token'}),isToken:true,keywords:['IMMUNE']}];const a=play(s,['token']);assert.ok(a.players[0].deck.some(c=>c.instanceId==='token'));});
test('field IMMUNE remains excluded from targeted new spells',()=>{for(const id of ['execution','push','forced-silence','life-exchange','forced-exchange']){const s=setup(id);s.players[1].board[0]!.keywords=['IMMUNE'];assert.equal(executeAction(s,{type:'PLAY_TECHNIQUE',playerId:'player-1',cardInstanceId:'spell'}).success,false);}});
test('every spell is present in AI legal actions with its required targets',()=>{for(const c of EPIC_TECHNIQUES){const s=setup(c.id.slice('epic-spell-'.length));if(c.name==='복귀')s.players[0].graveyard=[generateCardInstance(unit,{instanceId:'grave'})];assert.ok(getLegalActions(s,'player-1').some(a=>a.type==='PLAY_TECHNIQUE' && a.cardInstanceId==='spell'),c.name);}});
test('precommit paired exchange pays once and resolves after both targets',()=>{const s=setup('forced-exchange');const b=executeAction(s,{type:'BEGIN_TARGETED_ACTION',playerId:'player-1',action:{type:'PLAY_TECHNIQUE',cardInstanceId:'spell'}});assert.ok(b.success);assert.equal(b.state.players[0].currentGold,10);const c=executeAction(b.state,{type:'CONFIRM_PRECOMMIT_TARGET',playerId:'player-1',targetId:'ally'});assert.ok(c.success);assert.equal(c.state.players[0].currentGold,6);assert.equal(c.state.players[0].board[0]!.currentAttack,2);assert.deepEqual(c.state.targetingState!.validTargetIds,['enemy']);const d=executeAction(c.state,{type:'SELECT_EFFECT_TARGET',playerId:'player-1',targetId:'enemy'});assert.ok(d.success);assert.equal(d.state.players[0].currentGold,6);assert.equal(d.state.players[0].board[0]!.currentAttack,6);assert.equal(d.state.targetingState,undefined);});
