import assert from 'node:assert/strict';
import test from 'node:test';
import { createInitialGameState } from './create-initial-game-state';
import { generateCardInstance } from '../cards/generation';
import { executeAction, getLegalActions } from '../actions/engine-actions';
import { applyEffect, resolvePendingEffects } from '../effects/effect-engine';
import { canSelectAsAttacker } from './combat';
import { chooseBestAction } from '../actions/ai-evaluator';
import type { CardDefinition } from '../cards/types';
const base: CardDefinition = {id:'base',name:'base',cardType:'WRESTLER',cost:1,attack:2,health:3,rulesText:'',isToken:false,isChampionToken:false,keywords:[],abilities:[]};
const material: CardDefinition={...base,id:'fusion',attack:0,health:1,keywords:['FUSION'],abilities:[{trigger:'ON_FUSION',effects:[{type:'STRUCTURED',action:'DRAW',values:{amount:1}}]}]};
const host: CardDefinition={...base,id:'host',abilities:[{trigger:'ON_FUSION',effects:[{type:'DAMAGE_OPPONENT_CHAMPION',amount:1}]}]};
function setup(){
 const s=createInitialGameState(undefined,[base,material,host]);s.status='IN_PROGRESS';s.activePlayerId=s.players[0].id;s.players[0].currentGold=6;
 s.players[0].hand=[generateCardInstance(material,{instanceId:'material'})];
 s.players[0].board=[{...generateCardInstance(host,{instanceId:'host'}),boardSlot:0,enteredThisTurn:false},null,null,null];
 s.players[0].deck=[generateCardInstance(base,{instanceId:'drawn'})];return s;
}
function play(s=setup()){return executeAction(s,{type:'PLAY_WRESTLER',playerId:s.players[0].id,cardInstanceId:'material',boardSlot:1});}
function select(s:ReturnType<typeof setup>){return executeAction(s,{type:'SELECT_EFFECT_TARGET',playerId:s.players[0].id,targetId:'host'}).state;}
test('fusion requires existing ally and real free slot',()=>{
 const empty=setup();empty.players[0].board=[null,null,null,null];assert.equal(play(empty).success,false);
 const full=setup();for(let i=1;i<4;i++)full.players[0].board[i]={...generateCardInstance(base,{instanceId:'full'+i}),boardSlot:i as 1|2|3};assert.equal(play(full).success,false);assert.ok(!getLegalActions(full,full.players[0].id).some(a=>a.type==='PLAY_WRESTLER'));
});
test('0/1 source transfers stats, both triggers exactly once, then vanishes outside graveyard',()=>{
 const p=play();assert.ok(p.success);assert.equal(p.state.players[0].board[1]?.instanceId,'material');assert.deepEqual(p.state.targetingState?.validTargetIds,['host']);
 const s=select(p.state);assert.equal(s.players[0].board[0]?.currentAttack,2);assert.equal(s.players[0].board[0]?.currentHealth,4);assert.equal(s.players[0].board[0]?.maxHealth,4);
 assert.equal(s.players[0].hand[0]?.instanceId,'drawn');assert.equal(s.players[1].health,19);assert.equal(s.players[0].board[1],null);
 assert.equal(s.events.filter(e=>e.type==='FUSION').length,2);assert.equal(s.events.filter(e=>e.type==='CARD_VANISHED').length,1);
 assert.ok(!s.events.some(e=>e.type==='CARD_RETIRED'||e.type==='CARD_DESTROYED'));assert.equal(s.players[0].graveyard.length,0);assert.equal(s.players[0].removedFromGame.length,0);assert.ok(!s.targetingState);
 assert.ok(s.events.findIndex(e=>e.type==='CARD_DRAWN')<s.events.findIndex(e=>e.type==='CARD_VANISHED'));
 assert.deepEqual(select(s),s);
});
test('current source stats and wounded host maximum health increment',()=>{const s=setup();Object.assign(s.players[0].hand[0],{currentAttack:2,currentHealth:3,maxHealth:4});Object.assign(s.players[0].board[0]!,{currentHealth:2,maxHealth:4});const done=select(play(s).state);assert.equal(done.players[0].board[0]?.currentAttack,4);assert.equal(done.players[0].board[0]?.currentHealth,5);assert.equal(done.players[0].board[0]?.maxHealth,7);});
test('cancel restores exact pre-play state including entry effects',()=>{const s=setup();s.players[0].hand[0].abilities.unshift({trigger:'ENTER_FIELD',effects:[{type:'GAIN_GOLD',amount:2}]});const before=structuredClone(s);const p=play(s);assert.ok(p.success);const c=executeAction(p.state,{type:'CANCEL_EFFECT_TARGET',playerId:s.players[0].id});assert.deepEqual(c.state,before);assert.deepEqual(s,before);});
test('enemy and self cannot be fusion target',()=>{const p=play();for(const id of ['material',p.state.players[1].id,'forged'])assert.equal(executeAction(p.state,{type:'SELECT_EFFECT_TARGET',playerId:p.state.players[0].id,targetId:id}).success,false);});
test('repeat fusion on same host and reconnect choice',()=>{let s=select(JSON.parse(JSON.stringify(play().state)));s.players[0].hand.push(generateCardInstance(material,{instanceId:'material'}));s=select(play(s).state);assert.equal(s.players[0].board[0]?.currentHealth,5);assert.equal(s.players[0].board[0]?.fusionCount,2);assert.equal(s.events.filter(e=>e.type==='CARD_VANISHED').length,2);});
test('silenced source loses fusion keyword; silenced host receives stats but no ON_FUSION',()=>{const s=setup();s.players[0].hand[0].isSilenced=true;const played=play(s);assert.ok(played.success);assert.ok(!played.state.targetingState);assert.ok(played.state.players[0].board[1]);const t=setup();t.players[0].board[0]!.isSilenced=true;const done=select(play(t).state);assert.equal(done.players[1].health,20);assert.equal(done.players[0].board[0]?.currentHealth,4);});
test('entry effect removes all candidates: exact rollback and no targeting deadlock',()=>{const s=setup();s.players[0].hand[0].abilities.unshift({trigger:'ENTER_FIELD',effects:[{type:'STRUCTURED',action:'DESTROY',target:{zone:'BOARD',owner:'SELF',selection:'ALL',count:4,filter:{excludeSource:true}}}]});assert.deepEqual(play(s).state,s);});
test('nested ON_FUSION target choice keeps material until resolution and forbids play refund',()=>{const s=setup();s.players[0].hand[0].abilities=[{trigger:'ON_FUSION',effects:[{type:'STRUCTURED',action:'DAMAGE',target:{zone:'PLAYER',owner:'ENEMY',selection:'PLAYER_CHOICE',count:1},values:{amount:1}}]}];const p=select(play(s).state);assert.ok(p.targetingState);assert.ok(p.players[0].board[1]);assert.ok(!p.targetingState?.playRollback);const restored=JSON.parse(JSON.stringify(p));const done=executeAction(restored,{type:'SELECT_EFFECT_TARGET',playerId:s.players[0].id,targetId:s.players[1].id}).state;assert.equal(done.players[1].health,18);assert.equal(done.players[0].board[1],null);assert.ok(!done.targetingState);});
test('VANISH generic action removes field card without leave/death triggers, idempotent',()=>{const s=setup();s.players[0].board[0]!.abilities.push({trigger:'LEAVE_FIELD',effects:[{type:'GAIN_GOLD',amount:9}]});const effect={type:'STRUCTURED' as const,action:'VANISH' as const,target:{zone:'BOARD' as const,owner:'SELF' as const,selection:'ALL' as const,count:4}};const done=applyEffect(s,s.players[0].id,s.players[0].hand[0],effect);assert.equal(done.players[0].board[0],null);assert.equal(done.players[0].currentGold,6);assert.equal(done.players[0].graveyard.length,0);assert.deepEqual(applyEffect(done,s.players[0].id,s.players[0].hand[0],effect),done);});
for(const kind of ['PLAYER','WRESTLER'] as const)test('CANNOT_ATTACK blocks '+kind+' but not effect damage or active',()=>{const s=setup();s.players[0].board[0]!.keywords=['CANNOT_ATTACK'];s.players[1].board[0]={...generateCardInstance(base,{instanceId:'enemy'}),boardSlot:0};assert.equal(canSelectAsAttacker(s,s.players[0].id,'host'),false);assert.ok(!getLegalActions(s,s.players[0].id).some(a=>a.type==='ATTACK'&&a.attackerInstanceId==='host'));const result=executeAction(s,{type:'ATTACK',playerId:s.players[0].id,attackerInstanceId:'host',target:kind==='PLAYER'?{type:'PLAYER',playerId:s.players[1].id}:{type:'WRESTLER',playerId:s.players[1].id,cardInstanceId:'enemy'}});assert.equal(result.success,false);const done=applyEffect(s,s.players[0].id,s.players[0].board[0]!,{type:'DAMAGE_OPPONENT_CHAMPION',amount:2});assert.equal(done.players[1].health,18);});
test('dynamic add/remove and silence restore attack legality',()=>{let s=setup();const source=s.players[0].board[0]!;for(const action of ['ADD_KEYWORD','REMOVE_KEYWORD'] as const){s=applyEffect(s,s.players[0].id,source,{type:'STRUCTURED',action,target:{zone:'BOARD',owner:'SELF',selection:'SELF',count:1},values:{keyword:'CANNOT_ATTACK'}});assert.equal(canSelectAsAttacker(s,s.players[0].id,'host'),action==='REMOVE_KEYWORD');}s.players[0].board[0]!.keywords=['CANNOT_ATTACK'];s.players[0].board[0]!.isSilenced=true;assert.ok(canSelectAsAttacker(s,s.players[0].id,'host'));});
test('AI chooses legal fusion target and never attacks with CANNOT_ATTACK',()=>{const s=setup();s.players[0].board[0]!.keywords=['CANNOT_ATTACK'];const p=play(s).state;const actions=getLegalActions(p,p.players[0].id);for(const difficulty of [undefined,'NORMAL','HARD','BOSS'] as const){const action=chooseBestAction(p,actions,p.players[0].id,difficulty);assert.equal(action.type,'SELECT_EFFECT_TARGET');const done=executeAction(p,action);assert.ok(done.success);assert.ok(!done.state.targetingState);assert.ok(!getLegalActions(done.state,p.players[0].id).some(a=>a.type==='ATTACK'));}});


test('CANNOT_ATTACK permits active ability, fusion effects and retaliation',()=>{let s=setup();s.players[0].board[0]!.keywords=['CANNOT_ATTACK'];s.players[0].board[0]!.abilities.push({trigger:'ACTIVE',effects:[{type:'DAMAGE_OPPONENT_CHAMPION',amount:2}]});const active=executeAction(s,{type:'USE_ACTIVE',playerId:s.players[0].id,cardInstanceId:'host'});assert.ok(active.success);assert.equal(active.state.players[1].health,18);s.players[0].hand[0].keywords.push('CANNOT_ATTACK');const fused=select(play(s).state);assert.equal(fused.players[1].health,19);s.activePlayerId=s.players[1].id;s.players[1].board[0]={...generateCardInstance({...base,health:8},{instanceId:'enemy'}),boardSlot:0,enteredThisTurn:false};const attacked=executeAction(s,{type:'ATTACK',playerId:s.players[1].id,attackerInstanceId:'enemy',target:{type:'WRESTLER',playerId:s.players[0].id,cardInstanceId:'host'}});assert.ok(attacked.success);assert.equal(attacked.state.players[1].board[0]?.currentHealth,6);});
test('temporary attack restriction expires on turn end for either owner',()=>{for(const index of [0,1]){const s=setup();s.players[index].board[0]={...generateCardInstance(base,{instanceId:'temporary'}),boardSlot:0,enteredThisTurn:false};const source=s.players[0].hand[0];const granted=applyEffect(s,s.players[0].id,source,{type:'STRUCTURED',action:'ADD_KEYWORD',target:{zone:'BOARD',owner:index===0?'SELF':'ENEMY',selection:'ALL',count:4},values:{keyword:'CANNOT_ATTACK',duration:'THIS_TURN'}});assert.ok(granted.players[index].board[0]?.keywords.includes('CANNOT_ATTACK'));const ended=executeAction(granted,{type:'END_TURN',playerId:s.players[0].id});assert.ok(ended.success);assert.ok(!ended.state.players[index].board[0]?.keywords.includes('CANNOT_ATTACK'));}});
test('source remains through nested choices and cannot cancel committed fusion sequence',()=>{const s=setup();s.players[0].hand[0].abilities=[{trigger:'ON_FUSION',effects:[{type:'STRUCTURED',action:'BUFF',target:{zone:'BOARD',owner:'SELF',selection:'PLAYER_CHOICE',count:1},values:{attack:1,health:1}}]}];const committed=select(play(s).state);assert.ok(committed.players[0].board[1]);assert.ok(!getLegalActions(committed,s.players[0].id).some(a=>a.type==='CANCEL_EFFECT_TARGET'));assert.deepEqual(executeAction(committed,{type:'CANCEL_EFFECT_TARGET',playerId:s.players[0].id}).state,committed);const done=select(committed);assert.equal(done.players[0].board[0]?.currentAttack,3);assert.equal(done.players[0].board[1],null);});
test('target ON_FUSION can suspend without replaying source trigger',()=>{const s=setup();s.players[0].board[0]!.abilities=[{trigger:'ON_FUSION',effects:[{type:'STRUCTURED',action:'BUFF',target:{zone:'BOARD',owner:'SELF',selection:'PLAYER_CHOICE',count:1},values:{attack:1,health:0}}]}];const first=select(play(s).state);assert.equal(first.events.filter(e=>e.type==='CARD_DRAWN').length,1);assert.ok(first.targetingState?.validTargetIds.includes('material'));const restored=JSON.parse(JSON.stringify(first));const done=executeAction(restored,{type:'SELECT_EFFECT_TARGET',playerId:restored.players[0].id,targetId:'material'}).state;assert.equal(done.events.filter(e=>e.type==='CARD_DRAWN').length,1);assert.equal(done.events.filter(e=>e.type==='CARD_VANISHED').length,1);});
test('VANISH from hidden zones cannot be revived or recovered, does not pay wanted',()=>{for(const zone of ['HAND','DECK','GRAVEYARD'] as const){const s=setup(),source=s.players[0].hand[0];const doomed=generateCardInstance({...base,keywords:['WANTED']},{instanceId:'doomed'});s.players[1][zone==='HAND'?'hand':zone==='DECK'?'deck':'graveyard']=[doomed];const gone=applyEffect(s,s.players[0].id,source,{type:'STRUCTURED',action:'VANISH',target:{zone,owner:'ENEMY',selection:'ALL',count:4}});assert.ok(!JSON.stringify(gone.players).includes('doomed'));assert.equal(gone.players[0].nextTurnGoldBonus,0);assert.equal(gone.events.filter(e=>e.type==='CARD_VANISHED').length,1);assert.ok(!gone.events.some(e=>e.type==='CARD_RETIRED'||e.type==='CARD_DESTROYED'));}});
test('generic FUSION action resolves through shared effect engine',()=>{const s=setup();s.players[0].board[1]={...s.players[0].hand[0],boardSlot:1};s.players[0].hand=[];const result=applyEffect(s,s.players[0].id,s.players[0].board[1]!,{type:'STRUCTURED',action:'FUSION',target:{zone:'BOARD',owner:'SELF',selection:'SAME_TARGET',count:1}},['host']);assert.equal(result.players[0].board[0]?.currentHealth,4);assert.equal(result.players[0].board[1],null);});

test('fusion stat transfer invokes existing attack and health gain listeners before removal',()=>{
 const s=setup();Object.assign(s.players[0].hand[0],{currentAttack:2,currentHealth:3,maxHealth:3});
 s.players[0].board[0]!.abilities=[{trigger:'STAT_CHANGED',condition:{type:'ATTACK_GAIN'},effects:[{type:'STRUCTURED',action:'BUFF',target:{zone:'BOARD',owner:'SELF',selection:'SELF',count:1},values:{healthReference:'LAST_ATTACK_DELTA'}}]}];
 const done=select(play(s).state);assert.equal(done.players[0].board[0]?.currentAttack,4);assert.equal(done.players[0].board[0]?.currentHealth,8);assert.equal(done.players[0].board[0]?.maxHealth,8);assert.equal(done.players[0].board[1],null);
});
test('fusion accepts an immune ally without weakening normal effect targeting',()=>{
 const s=setup();s.players[0].board[0]!.keywords=['IMMUNE'];const played=play(s);assert.ok(played.success);const done=select(played.state);assert.equal(done.players[0].board[0]?.currentHealth,4);assert.equal(done.players[0].board[1],null);
});
test('permanent regrant does not expire with an earlier temporary attack restriction',()=>{
 let s=setup();const c=s.players[0].board[0]!;
 for(const duration of ['THIS_TURN','PERMANENT'] as const)s=applyEffect(s,s.players[0].id,c,{type:'STRUCTURED',action:'ADD_KEYWORD',target:{zone:'BOARD',owner:'SELF',selection:'SELF',count:1},values:{keyword:'CANNOT_ATTACK',duration}});
 const next=executeAction(s,{type:'END_TURN',playerId:s.players[0].id});assert.ok(next.success);assert.ok(next.state.players[0].board[0]?.keywords.includes('CANNOT_ATTACK'));
});
