import assert from 'node:assert/strict';
import test from 'node:test';
import {createInitialGameState} from './create-initial-game-state';
import {generateCardInstance} from '../cards/generation';
import {cardRecordToDefinition} from '../cards/published-cards';
import {applyEffect,resolveTriggeredAbilities,resolvePendingEffects} from '../effects/effect-engine';
import {executeAction} from '../actions/engine-actions';
import type {CardDefinition} from '../cards/types';
const text="카운트다운(3):'공격불가' 키워드를 제거하고, 필드에 있는 모든 '기계' 카드들을 전부 이 카드에 합체시킵니다! 그리고 '러쉬' 키워드를 추가합니다! 이 카드는 '도발'을 무시하고 상대 챔피언을 공격 할 수 있습니다!";
const base:CardDefinition={id:'base',name:'base',cardType:'WRESTLER',cost:1,attack:2,health:3,rulesText:'',keywords:[],abilities:[],tags:['기계'],status:'DRAFT',isToken:false,isChampionToken:false};
const rune=cardRecordToDefinition({id:'rune',name:'룬스달라이트 군주 루나',cardType:'WRESTLER',rarity:'CHAMPION',cost:6,attack:0,health:8,text,keywords:['IMMUNE','COUNTDOWN','CANNOT_ATTACK'],isToken:true,isChampionToken:true,effectId:null,effectConfig:{countdownTurns:3},status:'DRAFT',imageAssetId:null,imageUrl:null,version:1,createdAt:'',updatedAt:''});
function setup(){const s=createInitialGameState(undefined,[base,rune]);s.status='IN_PROGRESS';s.turn=3;s.activePlayerId='player-1';s.events=[];s.cardPool=[base,rune];for(const p of s.players){p.champion!.quest=null;p.hand=[];p.deck=[];p.board=[null,null,null,null];p.graveyard=[];}s.players[0].board[0]={...generateCardInstance(rune,{instanceId:'rune'}),boardSlot:0,enteredThisTurn:false};return s;}
const add=(s:ReturnType<typeof setup>,owner:number,slot:0|1|2|3,id:string,d=base)=>{const definition={...d,id:'definition:'+id};s.cardPool!.push(definition);return s.players[owner].board[slot]={...generateCardInstance(definition,{instanceId:id}),boardSlot:slot,enteredThisTurn:false};};
const fire=(s:ReturnType<typeof setup>)=>resolveTriggeredAbilities(s,'player-1',s.players[0].board[0]!,'COUNTDOWN');
test('current Rune text maps to machine fusion instead of the removed max-health attack bonus',()=>{assert.deepEqual(rune.abilities[0].effects.map(e=>e.type==='STRUCTURED'&&e.action),['REMOVE_KEYWORD','FUSION','ADD_KEYWORD','BUFF']);});
test('countdown absorbs both fields including immune machines; uses current ATK/HP and excludes self and hidden zones',()=>{const s=setup();add(s,0,1,'own',{...base,keywords:['IMMUNE']});add(s,1,0,'enemy',{...base,keywords:['IMMUNE'],attack:4,health:5});add(s,1,1,'non-machine',{...base,tags:['other']});s.players[0].board[1]!.currentHealth=1;s.players[0].hand=[generateCardInstance(base,{instanceId:'hand'})];s.players[1].deck=[generateCardInstance(base,{instanceId:'deck'})];const n=fire(s),host=n.players[0].board[0]!;assert.deepEqual([host.currentAttack,host.currentHealth,host.maxHealth],[6,14,14]);assert.equal(n.players[0].board[1],null);assert.equal(n.players[1].board[0],null);assert.ok(n.players[1].board[1]);assert.equal(n.players[0].hand[0].instanceId,'hand');assert.equal(n.players[1].deck[0].instanceId,'deck');assert.equal(n.events.filter(e=>e.type==='CARD_VANISHED').length,2);assert.equal(n.events.filter(e=>e.type==='FUSION').length,4);assert.equal(n.events.filter(e=>e.type==='CARD_RETIRED'||e.type==='CARD_DESTROYED').length,0);assert.equal(n.players.flatMap(p=>p.graveyard).length,0);assert.ok(host.ignoreTauntToChampion);assert.ok(host.keywords.includes('RUSH'));assert.ok(!host.keywords.includes('CANNOT_ATTACK'));assert.ok(!n.targetingState);});
test('enemy material retains its own effect owner and grants keywords to the exact opposing fusion host',()=>{const s=setup();const donor={...base,abilities:[{trigger:'ON_FUSION' as const,effects:[{type:'STRUCTURED' as const,action:'DRAW' as const,values:{amount:1}},{type:'STRUCTURED' as const,action:'ADD_KEYWORD' as const,target:{zone:'BOARD' as const,owner:'SELF' as const,selection:'FUSION_TARGET' as const,count:1},values:{keyword:'LIFESTEAL' as const}}]}]};add(s,1,0,'enemy',donor);s.players[1].deck=[generateCardInstance(base,{instanceId:'enemy-draw'})];const n=fire(s);assert.equal(n.players[1].hand[0].instanceId,'enemy-draw');assert.ok(n.players[0].board[0]!.keywords.includes('LIFESTEAL'));assert.equal(n.players[0].hand.length,0);});
test('batch resumes after nested choice/reconnect exactly once and only then grants rush',()=>{const s=setup();add(s,0,1,'choice',{...base,abilities:[{trigger:'ON_FUSION',effects:[{type:'STRUCTURED',action:'DAMAGE',target:{zone:'BOARD',owner:'ENEMY',selection:'PLAYER_CHOICE',count:1},values:{amount:1}}]}]});add(s,1,0,'later');add(s,1,1,'other',{...base,tags:[]});let n=fire(s);assert.ok(n.targetingState);assert.ok(n.players[0].board[1]);assert.ok(!n.players[0].board[0]!.keywords.includes('RUSH'));n=JSON.parse(JSON.stringify(n));const r=executeAction(n,{type:'SELECT_EFFECT_TARGET',playerId:'player-1',targetId:'other'});assert.ok(r.success);n=r.state;assert.equal(n.events.filter(e=>e.type==='CARD_VANISHED').length,2);assert.equal(n.players[0].board[0]!.currentAttack,4);assert.ok(n.players[0].board[0]!.keywords.includes('RUSH'));assert.deepEqual(resolvePendingEffects(n),n);});
test('no machines is safe; ordinary hand fusion still rejects enemy and self',()=>{const n=fire(setup());assert.equal(n.players[0].board[0]!.currentAttack,0);assert.ok(n.players[0].board[0]!.keywords.includes('RUSH'));assert.equal(n.events.filter(e=>e.type==='FUSION').length,0);const s=setup();add(s,1,0,'enemy');const blocked=applyEffect(s,'player-1',s.players[0].board[0]!,{type:'STRUCTURED',action:'FUSION',target:{zone:'BOARD',owner:'ENEMY',selection:'PLAYER_CHOICE',count:1}},['enemy']);assert.equal(blocked.events.filter(e=>e.type==='FUSION').length,0);});
test('silence disables countdown and removed collector stops the batch without touching remaining machines',()=>{const s=setup();s.players[0].board[0]!.isSilenced=true;add(s,1,0,'enemy');assert.equal(fire(s).players[1].board[0]!.instanceId,'enemy');const t=setup();add(t,0,1,'self-destruction',{...base,abilities:[{trigger:'ON_FUSION',effects:[{type:'STRUCTURED',action:'DESTROY',target:{zone:'BOARD',owner:'SELF',selection:'ALL',count:4}}]}]});add(t,1,0,'enemy');const n=fire(t);assert.equal(n.players[0].board[0],null);assert.ok(n.players[1].board[0]);assert.ok(!n.targetingState);});

