import test from 'node:test';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import { cardRecordToDefinition, type PublishedCardRecord } from '../cards/published-cards';
import { NEW_CARD_NAMES } from '../cards/new-card-effects';
import { generateCardInstance } from '../cards/generation';
import { createInitialGameState } from './create-initial-game-state';
import { executeAction } from '../actions/engine-actions';
import { applyEffect, getValidTargets, resolveTriggeredAbilities, resolvePendingEffects } from '../effects/effect-engine';
import { healNewCardAware } from './new-card-rules';
import { endTurn } from './turn-system';
import { attack } from './combat';
import { grantCardText } from '../cards/granted-text';
import { getLegalActions } from '../actions/engine-actions';
import { silenceCard } from './card-status';
import type { CardDefinition } from '../cards/types';

// Read-only production/admin snapshot, including actual names, keywords and armor.
const records = JSON.parse(readFileSync(new URL('../qa/fixtures/cards-2026-10-04.json', import.meta.url), 'utf8')) as PublishedCardRecord[];
function record(name:string):PublishedCardRecord { const r=records.find(r=>r.name===(name==='DEATH'?'1972년 11월 21일':name));assert.ok(r,name);return structuredClone(r); }
const specs=Object.fromEntries(NEW_CARD_NAMES.map(n=>{const r=record(n);return [n,[r.cost,r.attack,r.health]];}));
const unit:CardDefinition={id:'unit',name:'unit',cardType:'WRESTLER',cost:1,attack:2,health:10,rulesText:'',tags:['디 어쏘리티'],isToken:false,isChampionToken:false,keywords:[],abilities:[]};
function setup(name:string){const def=cardRecordToDefinition(record(name));const s=createInitialGameState();s.status='IN_PROGRESS';s.turn=3;s.activePlayerId='player-1';s.cardPool=[unit,...NEW_CARD_NAMES.map(n=>cardRecordToDefinition(record(n)))];s.players[0].currentGold=20;for(const p of s.players){p.health=30;p.maxHealth=30;}s.players[0].board[0]={...generateCardInstance(def,{instanceId:'source'}),boardSlot:0};s.players[1].board[0]={...generateCardInstance(unit,{instanceId:'enemy'}),boardSlot:0};s.players[1].deck=[generateCardInstance(unit,{instanceId:'draw'})];return s;}
function trigger(name:string,kind:'ENTER_FIELD'|'TURN_START'|'TURN_END'='ENTER_FIELD',prepare?:(s:ReturnType<typeof setup>)=>void){const s=setup(name);prepare?.(s);let a=resolveTriggeredAbilities(s,'player-1',s.players[0].board[0]!,kind);return settle(a);}

function settle(s:ReturnType<typeof setup>) {let a=s;for(let i=0;i<20&&a.targetingState?.active;i++){const id=a.targetingState.validTargetIds[0];if(!id){a=resolvePendingEffects(a);break;}const r=executeAction(a,{type:'SELECT_EFFECT_TARGET',playerId:a.targetingState.playerId,targetId:id});assert.ok(r.success);a=r.state;}return a;}
test('all current new records serialize without changing original cost/ATK/HP; explicit DSL wins',()=>{for(const n of NEW_CARD_NAMES){const r=record(n),copy=structuredClone(r);const d=cardRecordToDefinition(r);assert.equal(d.contentRule,n);assert.deepEqual([d.cost,d.attack,d.health],specs[n]);assert.deepEqual(r,copy);assert.equal(cardRecordToDefinition({...r,effectId:'ACTIVE_GAIN_GOLD',effectConfig:{amount:1}}).contentRule,undefined);}});
test('MPG selects an enemy and transfers 1 attack',()=>{const a=trigger('MPG');assert.equal(a.players[0].board[0]!.currentAttack,3);assert.equal(a.players[1].board[0]!.currentAttack,1);});
test('금구슬 uses current attack strictly below source; invalid targets rejected; DESTROY no grave',()=>{let s=setup('금구슬 마스터');const c=s.players[0].board[0]!,effect=c.abilities[0].effects[0];assert.deepEqual(getValidTargets(s,'player-1',c,effect),['enemy']);s.players[1].board[0]!.currentAttack=3;assert.deepEqual(getValidTargets(s,'player-1',c,effect),[]);s.players[1].board[0]!.currentAttack=2;const a=settle(resolveTriggeredAbilities(s,'player-1',c,'ENTER_FIELD'));assert.equal(a.players[1].board[0],null);assert.equal(a.players[1].graveyard.length,0);});
test('MK destroys only silenced enemies on owner turn start',()=>{const a=trigger('루나 MK.사일런스','TURN_START',s=>{s.players[1].board[0]!.isSilenced=true;s.players[1].board[1]={...generateCardInstance(unit,{instanceId:'safe'}),boardSlot:1};});assert.equal(a.players[1].board[0],null);assert.ok(a.players[1].board[1]);assert.equal(a.players[1].graveyard.length,0);});
test('루브 grows and gains taunt only when alone',()=>{const a=trigger('루브','TURN_END');assert.equal(a.players[0].board[0]!.currentAttack,3);assert.equal(a.players[0].board[0]!.maxHealth,4);assert.ok(a.players[0].board[0]!.keywords.includes('TAUNT'));const b=trigger('루브','TURN_END',s=>{s.players[0].board[1]=generateCardInstance(unit,{instanceId:'ally'});});assert.equal(b.players[0].board[0]!.currentAttack,2);});
test('루이나 generates authority wrestler and grants ally lifesteal only',()=>{const a=trigger('루이나');assert.equal(a.players[0].hand.length,1);assert.ok(a.players[0].hand[0].tags?.includes('디 어쏘리티'));assert.ok(a.players[0].board[0]!.keywords.includes('LIFESTEAL'));assert.ok(!a.players[1].board[0]!.keywords.includes('LIFESTEAL'));});
test('99 damage token wins against opponent champion',()=>{const a=trigger('반으로 갈라져 죽어!');assert.equal(a.status,'FINISHED');assert.equal(a.winnerId,'player-1');});
test('냥냥 펀치 distributes exactly 5 damage; deterministic and safe with no enemy wrestlers',()=>{const a=trigger('냥냥 펀치');assert.equal(a.events.filter(e=>e.type==='DAMAGE_DEALT').reduce((sum,e)=>sum+(e.amount??0),0),5);assert.deepEqual(a,trigger('냥냥 펀치'));const b=trigger('냥냥 펀치','ENTER_FIELD',s=>{s.players[1].board=[null,null,null,null];});assert.equal(b.players[1].health,25);});
test('vampire gains only damage actually dealt; armor/defense do not grant attack',()=>{const a=trigger('뱀파이어 왕자 MPG','ENTER_FIELD',s=>{s.players[1].board[1]={...generateCardInstance(unit,{instanceId:'armor'}),boardSlot:1,keywords:['ARMOR'],armor:1};});assert.equal(a.players[0].board[0]!.currentAttack,3);assert.equal(a.players[1].board[0]!.currentHealth,9);});
test('블랙 아웃 gains once per positive effect and combat damage, not armor-blocked damage',()=>{let s=setup('블랙 아웃');let a=applyEffect(s,'player-2',s.players[1].board[0]!,{type:'STRUCTURED',action:'DAMAGE',target:{zone:'BOARD',owner:'ENEMY',selection:'ALL',count:4},values:{amount:2}});assert.equal(a.players[0].board[0]!.currentAttack,2);s.players[0].board[0]!.keywords=['ARMOR'];s.players[0].board[0]!.armor=2;a=applyEffect(s,'player-2',s.players[1].board[0]!,{type:'STRUCTURED',action:'DAMAGE',target:{zone:'BOARD',owner:'ENEMY',selection:'ALL',count:4},values:{amount:1}});assert.equal(a.players[0].board[0]!.currentAttack,1);s=setup('블랙 아웃');const r=attack(s,'player-1','source',{type:'WRESTLER',playerId:'player-2',cardInstanceId:'enemy'});assert.ok(r.success);assert.equal(r.state.players[0].board[0]!.currentAttack,2);});
test('사일런스 reduces incoming damage by 2 only from silenced sources',()=>{for(const silenced of [true,false]){const s=setup('사일런스');s.players[1].board[0]!.isSilenced=silenced;const a=applyEffect(s,'player-2',s.players[1].board[0]!,{type:'STRUCTURED',action:'DAMAGE',target:{zone:'BOARD',owner:'ENEMY',selection:'ALL',count:4},values:{amount:3}});assert.equal(a.players[0].board[0]!.currentHealth,silenced?5:3);}});
test('어셈블 fills only available slots without replacing existing cards',()=>{const a=trigger('어셈블!!!','ENTER_FIELD',s=>{s.cardPool=[unit];});assert.equal(a.players[0].board.filter(Boolean).length,4);assert.equal(a.players[0].board[0]!.instanceId,'source');});
test('좀비 감염 transforms selected card while retaining current ATK/HP',()=>{const a=trigger('좀비 감염','ENTER_FIELD',s=>{s.players[1].board[0]!.currentAttack=7;s.players[1].board[0]!.currentHealth=8;});assert.equal(a.players[1].board[0]!.currentAttack,7);assert.equal(a.players[1].board[0]!.currentHealth,8);assert.equal(a.players[1].board[0]!.isToken,true);});
test('카산드라 buffs authority cards on both sides, grants regen and heals allied champion/field',()=>{const a=trigger('카산드라','ENTER_FIELD',s=>{s.cardPool=[...s.cardPool!,{...unit,tags:['디 어쏘리티']}];});assert.equal(a.players[0].board[0]!.maxHealth,3);assert.equal(a.players[1].board[0]!.maxHealth,11);assert.ok(a.players[1].board[0]!.keywords.includes('REGEN'));const b=trigger('카산드라','TURN_END',s=>{s.players[0].health=20;s.players[0].board[0]!.currentHealth=1;});assert.equal(b.players[0].health,21);assert.equal(b.players[0].board[0]!.currentHealth,2);});
test('헬뻑 damages all field wrestlers and no champions',()=>{const a=trigger('헬뻑','TURN_END');assert.equal(a.players[0].board[0]!.currentHealth,4);assert.equal(a.players[1].board[0]!.currentHealth,9);assert.equal(a.players[0].health,30);assert.equal(a.players[1].health,30);});
test('DEATH in hand loses without advancing turn; mine deals 5 and removes itself without retire',()=>{for(const name of ['DEATH','지뢰닷!!!']){const s=setup(name);s.players[0].hand=[s.players[0].board[0]!];s.players[0].board=[null,null,null,null];const r=endTurn(s,'player-1');assert.ok(r.success);if(name==='DEATH'){assert.equal(r.state.status,'FINISHED');assert.equal(r.state.loserId,'player-1');}else{assert.equal(r.state.players[0].health,25);assert.equal(r.state.players[0].hand.length,0);assert.equal(r.state.players[0].removedFromGame.length,1);assert.equal(r.state.players[0].graveyard.length,0);}}});
test('Casto converts only overflow to max HP and works for champion, field, lifesteal/regen; silence disables',()=>{let s=setup('카스토');s=healNewCardAware(s,'player-1',3);assert.equal(s.players[0].maxHealth,33);assert.equal(s.players[0].health,33);s=healNewCardAware(s,'player-1',2,'source');assert.equal(s.players[0].board[0]!.maxHealth,7);s.players[0].board[0]!.isSilenced=true;s=healNewCardAware(s,'player-1',2);assert.equal(s.players[0].maxHealth,33);assert.equal(s.overhealByTurn?.['3:player-1'],7);});
test('헬퍼 requires last turn overflow strictly greater than 5 and creates named token',()=>{for(const n of [5,6]){const a=trigger('헬퍼','TURN_START',s=>{s.overhealByTurn={'2:player-1':n,'1:player-1':99};});assert.equal(a.players[0].hand.length,n>5?1:0);if(n>5)assert.equal(a.players[0].hand[0].definitionId,record('냥냥 펀치').id);}});
test('힐빌 heals when it causally retires enemy, not destroy',()=>{const s=setup('힐빌');s.players[0].board[0]!.currentHealth=1;s.players[1].board[0]!.currentHealth=1;s.players[1].board[0]!.currentAttack=0;const r=attack(s,'player-1','source',{type:'WRESTLER',playerId:'player-2',cardInstanceId:'enemy'});assert.ok(r.success);assert.equal(r.state.players[0].board[0]!.currentHealth,3);});
test('Madokawa adds 3 wrestler damage then retires attacker with ordinary retire triggers',()=>{const s=setup('마도카와');s.players[0].board[1]={...generateCardInstance(unit,{instanceId:'attacker'}),boardSlot:1};const r=attack(s,'player-1','attacker',{type:'WRESTLER',playerId:'player-2',cardInstanceId:'enemy'});assert.ok(r.success);assert.equal(r.state.players[1].board[0]!.currentHealth,5);assert.equal(r.state.players[0].board[1],null);assert.ok(r.state.players[0].graveyard.some(c=>c.instanceId==='attacker'));});

test('copied new passive text remains executable after serialization and silence',()=>{let s=setup('카스토');const donor=s.cardPool!.find(d=>d.name==='카스토')!;s.players[0].board[0]=grantCardText({...generateCardInstance(unit,{instanceId:'copied'}),boardSlot:0,isSilenced:true},donor);s=JSON.parse(JSON.stringify(s));s=healNewCardAware(s,'player-1',2);assert.equal(s.players[0].maxHealth,32);});
test('AI sees legal new casts and rejects missing transform target',()=>{for(const name of ['냥냥 펀치','어셈블!!!','좀비 감염']){const s=setup(name);s.players[0].hand=[s.players[0].board[0]!];s.players[0].board=[null,null,null,null];assert.ok(getLegalActions(s,'player-1').some(a=>a.type==='PLAY_TECHNIQUE'&&a.cardInstanceId==='source'));if(name==='좀비 감염'){const empty=structuredClone(s);empty.players[1].board=[null,null,null,null];assert.ok(!getLegalActions(empty,'player-1').some(a=>a.type==='PLAY_TECHNIQUE'));assert.equal(executeAction(empty,{type:'PLAY_TECHNIQUE',playerId:'player-1',cardInstanceId:'source'}).success,false);}}});

test('all usable new techniques execute through actual hand cast and pay exact original cost',()=>{for(const name of ['냥냥 펀치','반으로 갈라져 죽어!','어셈블!!!','좀비 감염']){const s=setup(name),card=s.players[0].board[0]!;s.players[0].board=[null,null,null,null];s.players[0].hand=[card];s.cardPool=[unit,...s.cardPool!.filter(d=>d.name===name)];const r=executeAction(s,{type:'PLAY_TECHNIQUE',playerId:'player-1',cardInstanceId:'source'});assert.ok(r.success,name);const a=settle(r.state);assert.equal(a.players[0].currentGold,20-card.currentCost,name);if(name==='냥냥 펀치')assert.equal(a.events.filter(e=>e.type==='DAMAGE_DEALT').reduce((n,e)=>n+(e.amount??0),0),5);if(name==='좀비 감염')assert.equal(a.players[1].board[0]!.isToken,true);if(name==='어셈블!!!')assert.equal(a.players[0].board.filter(Boolean).length,4);}});

test('renamed defeat token keeps stable card ID binding and actual hand turn-end loss',()=>{
 const r=record('DEATH');assert.equal(r.name,'1972년 11월 21일');assert.equal(cardRecordToDefinition({...r,name:'또 다른 이름'}).contentRule,'DEATH');
 const s=setup('DEATH');s.players[0].hand=[s.players[0].board[0]!];s.players[0].board=[null,null,null,null];const result=endTurn(JSON.parse(JSON.stringify(s)),'player-1');assert.ok(result.success);assert.equal(result.state.loserId,'player-1');
});
test('마개조 selects only ally, buffs +1/+1 and grants real experiment-tag synergy without changing definition',()=>{
 const s=setup('마개조'),spell=s.players[0].board[0]!;s.players[0].board[0]={...generateCardInstance(unit,{instanceId:'ally'}),boardSlot:0};s.players[0].hand=[spell];
 const r=executeAction(s,{type:'PLAY_TECHNIQUE',playerId:'player-1',cardInstanceId:'source'});assert.ok(r.success);assert.deepEqual(r.state.targetingState?.validTargetIds,['ally']);
 let n=settle(r.state);assert.deepEqual([n.players[0].board[0]!.currentAttack,n.players[0].board[0]!.maxHealth],[3,11]);assert.deepEqual(n.players[0].board[0]!.grantedTags,['실험체']);assert.deepEqual(n.cardPool![0].tags,['디 어쏘리티']);
 const synergy={type:'STRUCTURED' as const,action:'BUFF' as const,target:{zone:'BOARD' as const,owner:'SELF' as const,selection:'ALL' as const,count:4,filter:{tagsAny:['실험체']}},values:{attack:1,health:1}};
 n=applyEffect(n,'player-1',generateCardInstance(unit,{instanceId:'caster'}),synergy);assert.equal(n.players[0].board[0]!.currentAttack,4);
 n=silenceCard(n,'ally');assert.equal(n.players[0].board[0]!.grantedTags,undefined);assert.equal(n.players[0].board[0]!.currentAttack,2);
});

test('태그 체인지 enforces two legal allied selections, swaps at same slot, pays only spell and buffs both cards',()=>{
 const s=setup('태그 체인지'),spell=s.players[0].board[0]!;s.players[0].board[0]={...generateCardInstance(unit,{instanceId:'field'}),boardSlot:0,currentCost:3,currentAttack:9,currentHealth:2,maxHealth:12};
 s.players[0].hand=[spell,generateCardInstance({...unit,cost:2},{instanceId:'hand'}),generateCardInstance({...unit,cost:4},{instanceId:'too-costly'})];
 let r=executeAction(s,{type:'PLAY_TECHNIQUE',playerId:'player-1',cardInstanceId:'source'});assert.ok(r.success);assert.deepEqual(r.state.targetingState?.validTargetIds,['field']);
 r=executeAction(r.state,{type:'SELECT_EFFECT_TARGET',playerId:'player-1',targetId:'field'});assert.ok(r.success);assert.deepEqual(r.state.targetingState?.validTargetIds,['hand']);assert.equal(executeAction(r.state,{type:'SELECT_EFFECT_TARGET',playerId:'player-1',targetId:'too-costly'}).success,false);
 const n=settle(r.state);assert.equal(n.players[0].currentGold,17);assert.equal(n.players[0].board[0]!.instanceId,'hand');assert.equal(n.players[0].board[0]!.currentAttack,3);const returned=n.players[0].hand.find(c=>c.instanceId==='field')!;assert.deepEqual([returned.currentAttack,returned.currentHealth,returned.maxHealth,returned.currentCost],[3,10,10,1]);assert.equal(n.players[0].graveyard.filter(c=>c.cardType==='WRESTLER').length,0);
 const empty=setup('태그 체인지');empty.players[0].hand=[empty.players[0].board[0]!];empty.players[0].board=[null,null,null,null];assert.equal(executeAction(empty,{type:'PLAY_TECHNIQUE',playerId:'player-1',cardInstanceId:'source'}).success,false);
});
