import assert from 'node:assert/strict';import test from 'node:test';
import {analyzeEffectText,isStructuredEffects as isStructuredEffectConfig,effectLibrary} from './structured-effects';
for(const keyword of ['합체','공격불가'])test('analyzer standalone '+keyword,()=>{const r=analyzeEffectText(keyword);assert.equal(r.status,'success');assert.deepEqual(r.keywords,[keyword==='합체'?'FUSION':'CANNOT_ATTACK']);});
test('source fusion text compiles draw with ON_FUSION and only printed fusion keyword',()=>{const r=analyzeEffectText('합체\n이 카드가 합체하면: 카드 1장을 드로우한다.');assert.equal(r.status,'success');assert.equal(r.effects[0]?.trigger,'ON_FUSION');assert.equal(r.effects[0]?.action,'DRAW');assert.deepEqual(r.keywords,['FUSION']);});
test('host ON_FUSION alone does not grant hand-play FUSION',()=>{const r=analyzeEffectText('이 카드가 합체하면: 상대 챔피언에게 1 피해.');assert.equal(r.status,'success');assert.equal(r.effects[0]?.trigger,'ON_FUSION');assert.equal(r.effects[0]?.action,'DAMAGE');assert.ok(!r.keywords.includes('FUSION'));});
test('entry and fusion text retain independent trigger order',()=>{const r=analyzeEffectText('합체\n등장: 카드 1장을 드로우한다.\n이 카드가 합체하면: 상대 챔피언에게 1 피해.');assert.equal(r.status,'success');assert.deepEqual(r.effects.map(e=>e.trigger),['ENTER_FIELD','ON_FUSION']);});
test('vanish target compiles separately from destroy/retire',()=>{const r=analyzeEffectText('등장: 상대 선수 1장을 소멸시킨다.');assert.equal(r.status,'success');assert.equal(r.effects[0]?.action,'VANISH');});
test('new runtime registry effects and trigger are administratively valid',()=>{const library=effectLibrary();assert.ok(library.triggers.some(t=>t.name==='ON_FUSION'&&t.status==='ACTIVE'));for(const action of ['VANISH','FUSION'])assert.ok(isStructuredEffectConfig({effects:[{trigger:'ENTER_FIELD',action,target:{zone:'BOARD',owner:'SELF',selection:'PLAYER_CHOICE',count:1}}]}));assert.ok(isStructuredEffectConfig({effects:[{trigger:'ENTER_FIELD',action:'ADD_KEYWORD',target:{zone:'BOARD',owner:'SELF',selection:'PLAYER_CHOICE',count:1},values:{keyword:'CANNOT_ATTACK',duration:'THIS_TURN'}}]}));});

