import assert from 'node:assert/strict';
import test from 'node:test';
import { completeMinionACatalog, minionACatalog, MINION_A_ID, MINION_A_TEXT } from './minion-a';
import { championRecordToDefinition, type PublishedChampionRecord } from './published-champions';
import { TEST_CHAMPIONS } from './test-champions';
import { createInitialGameState } from '../engine/create-initial-game-state';
import { executeAction, getLegalActions } from '../actions/engine-actions';
import { validateCardDefinitionReferences } from '../engine/card-definition-validation';
import { chooseBestAction, evaluateAction } from '../actions/ai-evaluator';
import { evaluateAction as legacyEvaluate } from '../actions/legacy-ai-evaluator';
import { runAITurn } from '../actions/ai-turn-scheduler';
import { getRandomCardGenerationCandidates } from '../cards/generation';

function record(id='public', extra: Record<string,unknown>={}) {return {id,name:id,cardType:'WRESTLER',cost:1,attack:2,health:3,text:'등장: 골드 1을 얻습니다.',keywords:[],tags:['시험'],isToken:false,isChampionToken:false,status:'PUBLISHED',effectId:'ENTER_FIELD_GAIN_GOLD',effectConfig:{amount:1},...extra};}
const champion=championRecordToDefinition({id:MINION_A_ID,name:'챔피언 미니언 A',maxHealth:20,abilityName:'완전히 무작위',abilityCost:2,abilityText:MINION_A_TEXT,abilityEffects:{effects:[{action:'GENERATE',target:{zone:'HAND',owner:'SELF',selection:'RANDOM',count:1,randomScope:'FULL'}}]},hasQuest:false,upgradedAbilityName:null,status:'PUBLISHED',version:1} as PublishedChampionRecord);
function fixture(records=[record()]) {const pool=minionACatalog(records);const state=createInitialGameState([MINION_A_ID,TEST_CHAMPIONS[0].id],minionACatalog([record('filler')]),[champion,TEST_CHAMPIONS[0]],undefined,{randomSeed:33,minionACardPool:pool});state.status='IN_PROGRESS';state.turn=3;state.activePlayerId='player-1';state.players[0].currentGold=5;state.players[0].hand=[];state.players[0].mulliganUsed=true;return state;}
const ability={type:'USE_CHAMPION_ABILITY' as const,playerId:'player-1'};
test('Minion A has exact text, cost 2 and no quest/reward/upgrade',()=>{assert.equal(champion.abilityCost,2);assert.equal(champion.ability.cost,2);assert.equal(champion.ability.description,MINION_A_TEXT);assert.equal(champion.quest,null);assert.equal(champion.upgradedAbility,null);});
test('legal actions and actual engine reject 0/1 gold, wrong turn, empty catalog; pay exactly 2 once',()=>{for(const gold of [0,1]){const s=fixture();s.players[0].currentGold=gold;assert.equal(getLegalActions(s,'player-1').some(a=>a.type===ability.type),false);assert.equal(executeAction(s,ability).success,false);assert.equal(s.players[0].currentGold,gold);}
const s=fixture();assert.ok(getLegalActions(s,'player-1').some(a=>a.type===ability.type));const r=executeAction(s,ability);assert.ok(r.success);assert.equal(r.state.players[0].currentGold,3);assert.equal(r.state.players[0].hand.length,1);assert.equal(executeAction(r.state,ability).success,false);const wrong=fixture();wrong.activePlayerId='player-2';assert.equal(executeAction(wrong,ability).success,false);const empty=fixture();empty.minionACardPool=[];assert.equal(executeAction(empty,ability).success,false);});
for(const [label,extra] of Object.entries({published:{},unpublished:{status:'DRAFT'},disabled:{status:'DISABLED'},token:{isToken:true,rarity:'TOKEN'},championToken:{isToken:true,isChampionToken:true,rarity:'CHAMPION'},deckIneligible:{deckEligible:false},spellToken:{cardType:'TECHNIQUE',attack:0,health:0,isToken:true,effectId:'STRUCTURED_EFFECTS_V1',effectConfig:{effects:[{trigger:'ACTIVE',action:'ADD_GOLD',values:{amount:1}}]}}})) {
 test(`actual generation and play: ${label}`,()=>{const raw=record(label,extra);const before=JSON.stringify(raw);const s=fixture([raw]);const generated=executeAction(s,ability);assert.ok(generated.success);const card=generated.state.players[0].hand[0];assert.ok(card);assert.equal(card.definitionId,label);assert.equal(card.isToken,raw.isToken);assert.equal(card.isChampionToken,raw.isChampionToken);assert.deepEqual(card.tags,['시험']);assert.equal(card.currentCost,1);assert.equal(card.isGenerated,true);assert.equal(JSON.stringify(raw),before);validateCardDefinitionReferences(JSON.parse(JSON.stringify(generated.state)));const play=executeAction(generated.state,card.cardType==='TECHNIQUE'?{type:'PLAY_TECHNIQUE',playerId:'player-1',cardInstanceId:card.instanceId}:{type:'PLAY_WRESTLER',playerId:'player-1',cardInstanceId:card.instanceId,boardSlot:0});assert.ok(play.success);assert.equal(play.state.players[0].currentGold,3,'pay card 1 and apply real +1 effect');assert.equal(play.state.players[0].hand.length,0);});
}
test('pool excludes only invalid records, deduplicates stable ids, keeps all valid categories',()=>{const valid=[record('normal'),record('draft',{status:'DRAFT'}),record('disabled',{status:'DISABLED'}),record('token',{isToken:true}),record('championToken',{isChampionToken:true,isToken:true}),record('spell',{cardType:'TECHNIQUE',health:0})];const broken=[null,{},record('deleted',{deletedAt:'today'}),record('missing',{name:null}),record('badStats',{cost:NaN}),record('admin',{cardType:'ADMIN'}),record('badEffects',{effectId:'STRUCTURED_EFFECTS_V1',effectConfig:{effects:[{trigger:'ACTIVE',action:'DOES_NOT_EXIST'}]}})];assert.deepEqual(minionACatalog([...valid,...valid,...broken]).map(d=>d.id),valid.map(d=>d.id).sort());assert.equal(getRandomCardGenerationCandidates(minionACatalog(valid),{randomScope:'FULL'}).length,valid.length);});
test('all valid ids reachable with same uniform shuffle algorithm; no category weights',()=>{const raw=[record('a'),record('b',{status:'DRAFT',cost:90}),record('c',{isToken:true}),record('d',{isChampionToken:true,isToken:true}),record('e',{cardType:'TECHNIQUE',health:0}),record('f',{status:'DISABLED',deckEligible:false})];const counts=new Map(raw.map(r=>[r.id,0]));for(let seed=0;seed<6000;seed++){const s=fixture(raw);s.randomSeed=seed;const r=executeAction(s,ability);assert.ok(r.success);const id=r.state.players[0].hand[0].definitionId;counts.set(id,counts.get(id)!+1);}for(const count of counts.values()) assert.ok(count>850&&count<1150,JSON.stringify([...counts]));});
test('full hand follows 7-card overflow removal, distinct generated instances and deterministic reconnect',()=>{const s=fixture();s.players[0].hand=s.players[0].deck.slice(0,7);const r=executeAction(s,ability);assert.ok(r.success);assert.equal(r.state.players[0].hand.length,7);assert.equal(r.state.players[0].removedFromGame.length,1);assert.ok(r.state.events.some(e=>e.reason==='OVERDRAW'));const first=fixture();const a=executeAction(first,ability);const b=executeAction(JSON.parse(JSON.stringify(first)),ability);assert.equal(JSON.stringify(a),JSON.stringify(b));const next=structuredClone(a.state);next.players[0].championAbilityUsedThisTurn=false;next.players[0].currentGold=2;const c=executeAction(next,ability);assert.notEqual(c.state.players[0].hand[0].instanceId,c.state.players[0].hand[1].instanceId);});
test('AI decisions never preview random outcome and do not change state or catalog',()=>{const a=fixture([record('weak')]);const b=fixture([record('god',{cost:0,attack:999,health:999})]);assert.equal(evaluateAction(a,ability,'player-1'),evaluateAction(b,ability,'player-1'));assert.equal(legacyEvaluate(a,ability,'player-1'),legacyEvaluate(b,ability,'player-1'));for(const difficulty of [undefined,'NORMAL','HARD','BOSS'] as const){const before=JSON.stringify(a);assert.equal(chooseBestAction(a,[ability,{type:'END_TURN',playerId:'player-1'}],'player-1',difficulty).type,ability.type);assert.equal(JSON.stringify(a),before);}});
test('no Minion A: initial state has no complete pool and ordinary generation remains unchanged',()=>{const pool=minionACatalog([record(),record('private',{status:'DRAFT',isToken:true})]);const s=createInitialGameState([TEST_CHAMPIONS[0].id,TEST_CHAMPIONS[1].id],pool,TEST_CHAMPIONS,undefined,{minionACardPool:pool});assert.equal(s.minionACardPool,undefined);assert.equal(getRandomCardGenerationCandidates(pool).length,1);});

test('complete catalog includes actual built-in Zombie, and its generated card plays with Zombie rules',()=>{const s=fixture();s.minionACardPool=completeMinionACatalog([]);assert.equal(s.minionACardPool.length,1);const r=executeAction(s,ability);assert.ok(r.success);const c=r.state.players[0].hand[0];assert.equal(c.definitionId,'ko-fallback-zombie-token');const played=executeAction(r.state,{type:'PLAY_WRESTLER',playerId:'player-1',cardInstanceId:c.instanceId,boardSlot:0});assert.ok(played.success);assert.equal(played.state.players[0].board[0]?.isToken,true);validateCardDefinitionReferences(JSON.parse(JSON.stringify(played.state)));});
test('generated special card resolves an unpublished summon dependency and reconnect validates it',()=>{const target=record('hidden-child',{status:'DRAFT',isToken:true});const parent=record('special-parent',{status:'DISABLED',effectId:'STRUCTURED_EFFECTS_V1',effectConfig:{effects:[{trigger:'ENTER_FIELD',action:'SUMMON',values:{definitionRef:{id:'hidden-child'},count:1}}]}});const s=fixture([parent]);s.minionACardPool=minionACatalog([parent,target]);let generated;for(let seed=0;seed<50;seed++){s.randomSeed=seed;const r=executeAction(s,ability);if(r.state.players[0].hand[0].definitionId==='special-parent'){generated=r;break;}}assert.ok(generated);const c=generated.state.players[0].hand[0];const played=executeAction(generated.state,{type:'PLAY_WRESTLER',playerId:'player-1',cardInstanceId:c.instanceId,boardSlot:0});assert.ok(played.success);assert.ok(played.state.players[0].board.some(c=>c?.definitionId==='hidden-child'));validateCardDefinitionReferences(JSON.parse(JSON.stringify(played.state)));});

test('generation never leaks the hidden choice by changing the ordinary catalog',()=>{const s=fixture([record('private',{status:'DRAFT'})]);const r=executeAction(s,ability);assert.ok(r.success);assert.deepEqual(r.state.cardPool,s.cardPool);validateCardDefinitionReferences(r.state);});

test('real AI turn scheduler uses Minion A, generates a card and finishes its turn at every difficulty',async()=>{for(const difficulty of ['NORMAL','HARD','BOSS'] as const){const s=fixture([record('expensive',{cost:20})]);s.players[0].currentGold=2;const actions:string[]=[];const result=await runAITurn(s,'player-1',{difficulty,wait:async()=>{},waitForPresentationIdle:async()=>{},isCancelled:()=>false,onState:()=>{},onAction:a=>actions.push(a.type)});assert.ok(actions.includes('USE_CHAMPION_ABILITY'));assert.equal(result.players[0].currentGold,0);assert.equal(result.players[0].hand.length,1);assert.equal(result.activePlayerId,'player-2');}});
