import { silenceCard } from '../engine/card-status';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { cardRecordToDefinition, type PublishedCardRecord } from '../cards/published-cards';
import { LUNA_ID, LUNA_RULES_TEXT } from '../cards/luna';
import { repairedLegacyCardKeywords } from '../cards/legacy-card-effect-repair';
import { generateCardInstance } from '../cards/generation';
import type { CardInstance } from '../cards/types';
import { createInitialGameState } from '../engine/create-initial-game-state';
import { executeAction } from '../actions/engine-actions';
import type { GameAction } from '../actions/types';
import { applyEffect, resolveTriggeredAbilities } from '../effects/effect-engine';
import { enterField } from '../engine/enter-field';
import { endTurn } from '../engine/turn-system';
import { drawCard } from '../engine/draw-card';
import type { GameState } from '../types/game-state';

// Current 94-card snapshot: published API plus read-only admin dialogs.
const records = JSON.parse(readFileSync(new URL('./fixtures/cards-2026-10-07-public.json', import.meta.url), 'utf8')) as PublishedCardRecord[];
const definitions = records.map(cardRecordToDefinition);
const def = (name: string) => { const d=definitions.find(x=>x.name===name); assert.ok(d,name); return d; };
const instance = (name: string, id=name, patch: Partial<CardInstance>={}) => ({...generateCardInstance(def(name),{instanceId:id,isGenerated:false}),...patch});
function setup(): GameState {
 const s=createInitialGameState(); s.cardPool=definitions; s.randomSeed=40123; s.status='IN_PROGRESS'; s.activePlayerId='player-1'; s.turn=3;
 for(const p of s.players){p.currentGold=120;p.health=20;p.hand=[];p.deck=[instance('리버덩크',`${p.id}-draw`)];p.graveyard=[];p.board=[null,null,null,null];}
 return s;
}
const onBoard=(s:GameState,name:string,slot=0,owner=0,patch:Partial<CardInstance>={})=>{const c=instance(name,`${owner}-${name}-${slot}`,{boardSlot:slot as 0|1|2|3,enteredThisTurn:false,...patch});s.players[owner].board[slot]=c;return c;};
function action(s:GameState,a:GameAction,preferred?:string): GameState {
 let r=executeAction(s,a);assert.equal(r.success,true,JSON.stringify(r.success?'':r)); let n=r.state;
 for(let i=0;n.targetingState?.active;i++){assert.ok(i<20,'target loop'); const t=n.targetingState;const id=preferred&&t.validTargetIds.includes(preferred)?preferred:t.validTargetIds.find(id=>!t.selectedTargetIds.includes(id));assert.ok(id,'valid target');r=executeAction(n,{type:'SELECT_EFFECT_TARGET',playerId:t.playerId,targetId:id});assert.equal(r.success,true);n=r.state;}
 return n;
}
function play(s:GameState,name:string,slot=0,target?:string):GameState {const id=s.players[0].board.some(c=>c?.instanceId==='source')?`source-${s.events.length}`:'source';s.players[0].hand.unshift(instance(name,id));return action(s,{type:'PLAY_WRESTLER',playerId:'player-1',cardInstanceId:id,boardSlot:slot as 0|1|2|3},target);}
const source=(s:GameState)=>s.players[0].board.find(c=>c?.instanceId==='source')!;
const buff=(s:GameState,c:CardInstance,attack=0,health=0)=>applyEffect(s,'player-1',c,{type:'STRUCTURED',action:'BUFF',target:{zone:'BOARD',owner:'SELF',selection:'SELF',count:1},values:{attack,health}});
const retire=(s:GameState,c:CardInstance,owner='player-1')=>applyEffect(s,owner,c,{type:'STRUCTURED',action:'RETIRE',target:{zone:'BOARD',owner:'SELF',selection:'SELF',count:1}});


test('all 85 latest records retain administrator text and base cost/attack/health',()=>{assert.equal(records.length,85);for(const r of records){const d=def(r.name);assert.deepEqual([d.cost,d.attack,d.health],[r.cost,r.attack,r.health],r.name);assert.equal(d.rulesText,r.text,r.name);}});
for(const r of records.filter(r=>r.cardType==='WRESTLER'))test('latest hand play and state restore: '+r.name,()=>{const s=setup();onBoard(s,'리버덩크',0,1);s.players[0].graveyard=[instance('리버덩크','grave')];const n=play(s,r.name,1);assert.ok(n.events.some(e=>e.type==='CARD_PLAYED'));assert.equal(JSON.stringify(JSON.parse(JSON.stringify(n))),JSON.stringify(n));});
test('base-cost six still qualifies after discount; inflated cheaper card does not',()=>{const s=setup();s.players[0].hand=[instance('디 오리진','six',{currentCost:4}),instance('로드','three',{currentCost:7})];s.players[0].deck=[instance('디 오리진','deck')];const n=play(s,'도금구슬 마스터');assert.equal(n.players[0].hand[0].currentCost,3);assert.equal(n.players[0].hand[1].currentCost,7);assert.equal(n.players[0].deck[0].currentCost,6);});
test('Calavera revives eligible wrestler and grants taunt to that instance only',()=>{const s=setup();s.players[0].graveyard=[instance('리버덩크','grave')];onBoard(s,'로드',2);const n=play(s,'라 칼라베라');const revived=n.players[0].board.find(c=>c?.instanceId==='grave');assert.ok(revived?.keywords.includes('TAUNT'));assert.ok(!n.players[0].board[2]?.keywords.includes('TAUNT'));});
for(const [name,tag,atk,hp,regen] of [['팬텀워커','스트리트',1,1,false],['매드 사이언티스트 퍼플레인','실험체',1,1,true],['카산드라','디 어쏘리티',0,1,true]] as const)test(name+' buffs own hand/field only',()=>{const s=setup();const d=definitions.find(d=>d.tags?.includes(tag)&&d.name!==name)!;const c=instance(d.name,'tagged');s.players[0].hand=[{...c,instanceId:'hand'}];s.players[0].deck=[{...c,instanceId:'deck'}];s.players[0].graveyard=[{...c,instanceId:'grave'}];s.players[0].board[1]={...c,instanceId:'field',boardSlot:1};s.players[1].board[1]={...c,instanceId:'enemy',boardSlot:1};const n=play(s,name);for(const got of [n.players[0].hand[0],n.players[0].board[1]!]){assert.equal(got.currentAttack,c.currentAttack+atk);assert.equal(got.maxHealth,c.maxHealth+hp);if(regen)assert.ok(got.keywords.includes('REGEN'));}for(const got of [n.players[0].deck[0],n.players[0].graveyard[0],n.players[1].board[1]!]){assert.equal(got.currentAttack,c.currentAttack);assert.equal(got.maxHealth,c.maxHealth);}});
test('MK silence on play; destroy at own turn end only; no graveyard',()=>{const s=setup();onBoard(s,'로드',0,1);let n=play(s,'루나 MK.사일런스',0,'1-로드-0');assert.ok(n.players[1].board[0]?.isSilenced);n=resolveTriggeredAbilities(n,'player-1',source(n),'TURN_START');assert.ok(n.players[1].board[0]);n=resolveTriggeredAbilities(n,'player-1',source(n),'TURN_END');assert.equal(n.players[1].board[0],null);assert.equal(n.players[1].graveyard.length,0);});
test('Helper generates on enter and overflow strictly above three, without duplicating entry',()=>{for(const overflow of [3,4]){let n=play(setup(),'헬퍼');assert.equal(n.players[0].hand.length,1);n.overhealByTurn={'2:player-1':overflow};n=resolveTriggeredAbilities(n,'player-1',source(n),'TURN_START');assert.equal(n.players[0].hand.length,overflow===3?1:2);}});
test('Madokawa gives +2 outgoing combat, +1 incoming other allies and never retires attacker',()=>{const s=setup();onBoard(s,'마도카와',0);const a=onBoard(s,'로드',1,0,{currentAttack:2,currentHealth:10,maxHealth:10});const e=onBoard(s,'로드',0,1,{currentAttack:2,currentHealth:10,maxHealth:10});const n=action(s,{type:'ATTACK',playerId:'player-1',attackerInstanceId:a.instanceId,target:{type:'WRESTLER',playerId:'player-2',cardInstanceId:e.instanceId}} as GameAction);assert.equal(n.players[1].board[0]?.currentHealth,6);assert.equal(n.players[0].board[1]?.currentHealth,7);assert.equal(n.players[0].graveyard.length,0);});
test('Madokawa incoming effect damage excludes itself and silence removes aura',()=>{for(const silenced of [false,true]){const s=setup();const aura=onBoard(s,'마도카와',0,0,{isSilenced:silenced,currentHealth:10,maxHealth:10});onBoard(s,'로드',1,0,{currentHealth:10,maxHealth:10});const e=onBoard(s,'로드',0,1);const n=applyEffect(s,'player-2',e,{type:'STRUCTURED',action:'DAMAGE',target:{zone:'BOARD',owner:'ENEMY',selection:'ALL',count:4},values:{amount:2}});assert.equal(n.players[0].board[0]?.currentHealth,8);assert.equal(n.players[0].board[1]?.currentHealth,silenced?8:7);assert.ok(aura);}});

test('damage preparation that removes a target does not damage or retire its stale snapshot twice',()=>{const s=setup();const e=onBoard(s,'로드',0,1);const c=onBoard(s,'로드',0);c.abilities=[{trigger:'BEFORE_DAMAGE',effects:[{type:'STRUCTURED',action:'RETIRE',target:{zone:'BOARD',owner:'SELF',selection:'SELF',count:1}}]}];const n=applyEffect(s,'player-2',e,{type:'STRUCTURED',action:'DAMAGE',target:{zone:'BOARD',owner:'ENEMY',selection:'ALL',count:4},values:{amount:1}});assert.equal(n.players[0].board[0],null);assert.equal(n.players[0].graveyard.filter(x=>x.instanceId===c.instanceId).length,1);assert.equal(n.events.filter(e=>e.type==='CARD_RETIRED'&&e.cardInstanceId===c.instanceId).length,1);assert.equal(n.events.filter(e=>e.type==='DAMAGE_DEALT'&&e.target?.type==='CARD'&&e.target.cardInstanceId===c.instanceId).length,0);});
for(const r of records.filter(r=>r.cardType==='TECHNIQUE'))test('latest technique hand cast: '+r.name,()=>{const s=setup();const a=onBoard(s,'로드',0,0,{currentCost:1,currentHealth:2});onBoard(s,'로드',0,1);onBoard(s,'리버덩크',1,1);s.players[0].hand=[instance(r.name,'spell'),instance('로드','hand',{currentCost:1})];s.players[0].graveyard=[instance('로드','grave')];const n=action(s,{type:'PLAY_TECHNIQUE',playerId:'player-1',cardInstanceId:'spell'});assert.ok(n.events.some(e=>e.type==='CARD_PLAYED'&&e.cardInstanceId==='spell'));assert.ok(a);});

test('Madokawa effect damage +2 applies only to wrestlers; aura disappears with source',()=>{for(const spell of [false,true]){const s=setup();onBoard(s,'마도카와',0);const c=instance(spell?'냥냥 펀치':'로드','caster');const target=onBoard(s,'로드',0,1,{currentHealth:10,maxHealth:10});const fx={type:'STRUCTURED' as const,action:'DAMAGE' as const,target:{zone:'BOARD' as const,owner:'ENEMY' as const,selection:'ALL' as const,count:4},values:{amount:1}};const n=applyEffect(s,'player-1',c,fx);assert.equal(n.players[1].board[0]?.currentHealth,spell?9:7);s.players[0].board[0]=null;assert.equal(applyEffect(s,'player-1',c,fx).players[1].board[0]?.currentHealth,9);assert.ok(target);}});
test('Madokawa vulnerability preserves armor and defense prevention, and does not turn zero into damage',()=>{for(const kind of ['zero','armor','defense'] as const){const s=setup();onBoard(s,'마도카와',0);const c=onBoard(s,'로드',1,0,{currentHealth:10,maxHealth:10,...(kind==='defense'?{keywords:['DEFENSE'],enteredThisTurn:true,defenseUntilTurn:4}:kind==='armor'?{keywords:['ARMOR'],armor:2}:{})});const e=onBoard(s,'로드',0,1,{currentAttack:kind==='zero'?0:1,currentHealth:10,maxHealth:10});const n=kind==='defense'?applyEffect(s,'player-2',e,{type:'STRUCTURED',action:'DAMAGE',target:{zone:'BOARD',owner:'ENEMY',selection:'PLAYER_CHOICE',count:1},values:{amount:1}},[c.instanceId]):action(s,{type:'ATTACK',playerId:'player-1',attackerInstanceId:c.instanceId,target:{type:'WRESTLER',playerId:'player-2',cardInstanceId:e.instanceId}});assert.equal(n.players[0].board[1]?.currentHealth,10,kind);}});

test('zombie Bellona lethal spell hit retires exactly once despite its damage summon',()=>{const s=setup();const c=onBoard(s,'좀비 벨로나',0,1,{currentHealth:1});const source=onBoard(s,'로드',0);const n=applyEffect(s,'player-1',source,{type:'STRUCTURED',action:'DAMAGE',target:{zone:'BOARD',owner:'ENEMY',selection:'ALL',count:4},values:{amount:1}});assert.equal(n.players[1].graveyard.filter(x=>x.instanceId===c.instanceId).length,1);assert.equal(n.events.filter(e=>e.type==='CARD_RETIRED'&&e.cardInstanceId===c.instanceId).length,1);assert.equal(n.events.filter(e=>e.type==='DAMAGE_DEALT'&&e.target?.type==='CARD'&&e.target.cardInstanceId===c.instanceId).length,1);assert.equal(n.players[1].board.filter(c=>c?.definitionId===def('좀비').id).length,1);});
