CREATE TABLE IF NOT EXISTS "champions" (
  "id" text PRIMARY KEY NOT NULL,
  "name" text NOT NULL,
  "description" text DEFAULT '' NOT NULL,
  "image_asset_id" text,
  "image_url" text,
  "max_health" integer DEFAULT 20 NOT NULL,
  "ability_name" text NOT NULL,
  "ability_cost" integer DEFAULT 0 NOT NULL,
  "ability_text" text DEFAULT '' NOT NULL,
  "ability_effects" jsonb NOT NULL,
  "has_quest" boolean DEFAULT false NOT NULL,
  "quest_name" text,
  "quest_text" text,
  "quest_condition" jsonb,
  "quest_progress_required" integer,
  "quest_reward_text" text,
  "quest_reward_effects" jsonb,
  "upgraded_ability_name" text,
  "upgraded_ability_cost" integer,
  "upgraded_ability_text" text,
  "upgraded_ability_effects" jsonb,
  "champion_token_definition_id" text,
  "ability_audio_asset_id" text,
  "ability_audio_url" text,
  "ability_audio_volume" integer DEFAULT 100 NOT NULL,
  "status" text DEFAULT 'DRAFT' NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);