
import { useEffect, useState } from "react";
import { fetchRewardCatalogs, type RewardCatalogCard, type RewardCatalogPack, type RewardCatalogChampion } from "@/lib/rewards-client";
type Reward = {rewardType:string;rewardAmount:number;rewardTargetId:string|null};
type Definition = {id?:string;title:string;description:string;objectiveType:string;cardType:string|null;targetValue:number;enabled:boolean;condition?:unknown;platform:{questType:"DAILY"|"SEASON";seasonId:string|null;weight:number;modes:string[];rarity:string|null;result:string;activationAt:string|null;archived:boolean;version?:number;rewards:Reward[]}};
type Season = {id:string;name:string;startsAt:string;endsAt:string;status:string};
type Data = {definitions:Definition[];seasons:Season[];settings:{dailyCount:number;timezone:string};objectives:string[];modes:string[];audits:Array<{id:string;action:string;entityId:string;createdAt:string}>};
const labels:Record<string,string>={PLAY_MATCH:"경기 완료",WIN_MATCH:"경기 승리",LOSS_MATCH:"경기 패배",CARD_PLAYED:"카드 사용",WRESTLER_PLAYED:"선수 사용",TECHNIQUE_PLAYED:"주문 사용",CARD_RETIRED:"선수 리타이어",CARD_DESTROYED:"선수 파괴",DAMAGE_DEALT:"피해 주기",CHAMPION_ABILITY_USED:"챔피언 고유 능력",FUSION:"합체",ATTACK_DECLARED:"공격 선언"};
const base=import.meta.env.BASE_URL.replace(/\/$/,"")+"/api/admin/quests";
async function api<T>(path="",body?:unknown,method="POST"):Promise<T>{
 const response=await fetch(base+path,{credentials:"include",method:body===undefined?"GET":method,headers:{"Content-Type":"application/json"},...(body===undefined?{}:{body:JSON.stringify(body)})});
 const result=await response.json();if(!response.ok)throw new Error(result.message??"퀘스트 요청 실패");return result;
}
const fresh=(questType:"DAILY"|"SEASON"):Definition=>({title:"",description:"",objectiveType:"PLAY_MATCH",cardType:null,targetValue:1,enabled:true,platform:{questType,seasonId:null,weight:100,modes:["AI","PVP","TOWER","DRAFT"],rarity:null,result:"ANY",activationAt:null,archived:false,rewards:[{rewardType:"CURRENCY",rewardAmount:100,rewardTargetId:null}]}});
const control="mt-1 min-h-11 w-full border border-neutral-700 bg-black px-3 py-2 text-sm text-white";
const button="min-h-11 border border-amber-600 px-4 py-2 text-sm font-bold text-amber-200 disabled:opacity-40";
function localTime(iso:string){const d=new Date(iso);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export function AdminQuestManager(){
 const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState<"DAILY"|"SEASON">("DAILY"),[draft,setDraft]=useState<Definition>(fresh("DAILY"));
 const [message,setMessage]=useState(""),[busy,setBusy]=useState(false),[preview,setPreview]=useState(false),[advanced,setAdvanced]=useState(""),[catalog,setCatalog]=useState<{cards:RewardCatalogCard[];packs:RewardCatalogPack[];champions:RewardCatalogChampion[]}>({cards:[],packs:[],champions:[]});
 const [season,setSeason]=useState({id:"",name:"",startsAt:"",endsAt:"",status:"ACTIVE"});
 const [test,setTest]=useState({objectiveType:"CARD_PLAYED",amount:1,mode:"AI",cardType:"WRESTLER",rarity:"NORMAL",result:"WIN"});
 const [diagnostic,setDiagnostic]=useState<Array<{id:string;title:string;increment:number;reason:string}>>([]);
 async function load(){try{setData(await api<Data>());}catch(e){setMessage(e instanceof Error?e.message:"조회 실패");}}
 useEffect(()=>{void load();void fetchRewardCatalogs().then(setCatalog).catch(()=>{});},[]);
 function edit(d:Definition){setDraft(structuredClone(d));setTab(d.platform.questType);setAdvanced(d.condition?JSON.stringify(d.condition,null,2):"");}
 function platform(p:Partial<Definition["platform"]>){setDraft({...draft,platform:{...draft.platform,...p}});}
 async function action(run:()=>Promise<unknown>){setBusy(true);try{await run();await load();setMessage("저장했습니다. 이미 배정된 퀘스트의 조건·보상은 유지됩니다.");}catch(e){setMessage(e instanceof Error?e.message:"저장 실패");}finally{setBusy(false);}}
 async function save(){await action(()=>api("/definitions",{...draft,schemaVersion:advanced.trim()?"QUEST_CONDITION_V2":"QUEST_CONDITION_V1",condition:advanced.trim()?JSON.parse(advanced):null}));}
 function rewardChange(index:number,p:Partial<Reward>){platform({rewards:draft.platform.rewards.map((r,i)=>i===index?{...r,...p}:r)});}
 const rewardText=(r:Reward)=>r.rewardType==="CURRENCY"?r.rewardAmount.toLocaleString()+" 크레딧":((r.rewardType==="PACK"?catalog.packs: r.rewardType==="CARD"?catalog.cards:catalog.champions).find(i=>i.id===r.rewardTargetId)?.name ?? "보상 선택") + " ×"+r.rewardAmount;
 return <section className="space-y-6 text-neutral-100"><header><p className="text-xs tracking-widest text-amber-300">QUEST MANAGEMENT</p><h2 className="mt-2 text-2xl font-black">퀘스트 관리</h2><p className="mt-2 text-sm text-neutral-400">조건과 보상은 배정 시 고정됩니다. 비활성화·보관은 새 배정과 진행만 중단하며 기록을 삭제하지 않습니다.</p></header>
 {message&&<p role="status" className="border-l-2 border-amber-400 p-3">{message}</p>}
 <div className="flex flex-wrap gap-2">{(["DAILY","SEASON"] as const).map(t=><button key={t} className={button+(tab===t?" bg-amber-400 text-black":"")} onClick={()=>{setTab(t);setDraft(fresh(t));setAdvanced("");}}>{t==="DAILY"?"일일 퀘스트":"시즌 퀘스트"}</button>)}</div>
 {data&&<section className="border-y border-neutral-800 py-4"><h3 className="font-bold">배정 설정</h3><div className="grid gap-3 sm:grid-cols-3"><label>하루 퀘스트 수<input className={control} type="number" min="1" max="20" value={data.settings?.dailyCount??3} onChange={e=>setData({...data,settings:{...data.settings,dailyCount:Number(e.target.value)}})}/></label><label>초기화 시간대<select className={control} value={data.settings?.timezone??"Asia/Seoul"} onChange={e=>setData({...data,settings:{...data.settings,timezone:e.target.value}})}><option>Asia/Seoul</option><option>UTC</option></select></label><button disabled={busy} className={button} onClick={()=>void action(()=>api("/settings",data.settings,"PUT"))}>설정 저장</button></div><p className="mt-2 text-xs text-neutral-500">선택한 시간대의 00:00에 다음 일일 기간이 시작됩니다.</p></section>}
 <section className="space-y-2">{data?.definitions.filter(d=>d.platform.questType===tab && data.objectives.includes(d.objectiveType)).map(d=><div key={d.id} className="flex flex-wrap items-center justify-between gap-2 border-b border-neutral-800 py-3"><div><b>{d.title}</b><p className="text-xs text-neutral-400">v{d.platform.version} · {d.platform.archived?"보관":d.enabled?"활성":"비활성"} · 목표 {d.targetValue}</p></div><div className="flex gap-2"><button className={button} onClick={()=>edit(d)}>수정</button><button disabled={busy} className={button} onClick={()=>void action(()=>api("/definitions",{...d,enabled:!d.enabled}))}>{d.enabled?"비활성화":"활성화"}</button><button disabled={busy||d.platform.archived} className={button} onClick={()=>void action(()=>api("/definitions",{...d,enabled:false,platform:{...d.platform,archived:true}}))}>보관</button></div></div>)}</section>
 <button className={button} onClick={()=>{setDraft(fresh(tab));setAdvanced("");}}>새 퀘스트</button>
 <form onSubmit={e=>{e.preventDefault();void save();}} className="space-y-4 border border-neutral-800 p-4">
 <h3 className="font-black">{draft.id?"퀘스트 수정":"퀘스트 생성"}</h3>
 <div className="grid gap-4 sm:grid-cols-2"><label>이름<input required className={control} maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>목표량<input required className={control} type="number" min="1" max="100000000" value={draft.targetValue} onChange={e=>setDraft({...draft,targetValue:Number(e.target.value)})}/></label></div>
 <label className="block">설명<textarea className={control} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>
 <div className="grid gap-4 sm:grid-cols-2"><label>이벤트<select className={control} value={draft.objectiveType} onChange={e=>setDraft({...draft,objectiveType:e.target.value})}>{data?.objectives.map(o=><option key={o} value={o}>{labels[o]??o}</option>)}</select></label>
 {tab==="DAILY"?<label>등장 가중치<input className={control} type="number" min="1" max="100000" value={draft.platform.weight} onChange={e=>platform({weight:Number(e.target.value)})}/></label>:<label>시즌<select required className={control} value={draft.platform.seasonId??""} onChange={e=>platform({seasonId:e.target.value})}><option value="">시즌 선택</option>{data?.seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}</div>
 <fieldset><legend>허용 모드</legend><div className="mt-2 flex flex-wrap gap-4">{data?.modes.map(m=><label key={m}><input type="checkbox" checked={draft.platform.modes.includes(m)} onChange={e=>platform({modes:e.target.checked?[...draft.platform.modes,m]:draft.platform.modes.filter(x=>x!==m)})}/> {m}</label>)}</div></fieldset>
 <div className="grid gap-4 sm:grid-cols-3"><label>카드 종류<select className={control} value={draft.cardType??""} onChange={e=>setDraft({...draft,cardType:e.target.value||null})}><option value="">전체</option><option value="WRESTLER">선수</option><option value="TECHNIQUE">주문</option></select></label><label>등급<select className={control} value={draft.platform.rarity??""} onChange={e=>platform({rarity:e.target.value||null})}><option value="">전체</option>{["NORMAL","EPIC","LEGENDARY","CHAMPION"].map(r=><option key={r}>{r}</option>)}</select></label><label>경기 결과<select className={control} value={draft.platform.result} onChange={e=>platform({result:e.target.value})}><option value="ANY">전체</option><option value="WIN">승리</option><option value="LOSS">패배</option></select></label></div>
 <label className="block">활성화 시작 시점 (선택 · 현재 기기 시간)<input type="datetime-local" className={control} value={draft.platform.activationAt?localTime(draft.platform.activationAt):""} onChange={e=>platform({activationAt:e.target.value?new Date(e.target.value).toISOString():null})}/></label>
 <fieldset className="space-y-2"><legend className="font-bold">보상</legend>{draft.platform.rewards.map((r,i)=>{const options=r.rewardType==="PACK"?catalog.packs:r.rewardType==="CARD"?catalog.cards.filter(c=>!c.isToken&&!c.isChampionToken):catalog.champions;return <div key={i} className="grid gap-2 sm:grid-cols-4"><select aria-label={"보상 종류 "+(i+1)} className={control} value={r.rewardType} onChange={e=>rewardChange(i,{rewardType:e.target.value,rewardTargetId:null,rewardAmount:e.target.value==="CHAMPION"?1:r.rewardAmount})}><option value="CURRENCY">크레딧</option><option value="PACK">팩</option><option value="CARD">카드</option><option value="CHAMPION">챔피언</option></select>{r.rewardType!=="CURRENCY"&&<select required aria-label={"보상 대상 "+(i+1)} className={control} value={r.rewardTargetId??""} onChange={e=>rewardChange(i,{rewardTargetId:e.target.value})}><option value="">선택</option>{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>}<input aria-label={"보상 수량 "+(i+1)} className={control} type="number" min="1" value={r.rewardAmount} onChange={e=>rewardChange(i,{rewardAmount:Number(e.target.value)})}/><button type="button" disabled={draft.platform.rewards.length===1} className={button} onClick={()=>platform({rewards:draft.platform.rewards.filter((_,n)=>n!==i)})}>제거</button></div>;})}<button type="button" disabled={draft.platform.rewards.length>=10} className={button} onClick={()=>platform({rewards:[...draft.platform.rewards,{rewardType:"CURRENCY",rewardAmount:100,rewardTargetId:null}]})}>+ 보상 추가</button></fieldset>
 <details><summary>확장 조건 JSON (태그·소유자·수치 조건)</summary><textarea aria-label="확장 조건 JSON" className={control+" h-40 font-mono"} value={advanced} onChange={e=>setAdvanced(e.target.value)}/><p className="text-xs text-neutral-500">QUEST_CONDITION_V2 형식. required는 목표량과 같아야 합니다. 비워두면 선택한 이벤트 조건을 사용합니다.</p></details>
 <label className="block"><input type="checkbox" checked={draft.enabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/> 활성화</label>
 <div className="flex gap-2"><button disabled={busy} className={button}>저장</button><button type="button" className={button} onClick={()=>setPreview(!preview)}>미리보기</button></div>
 {preview&&<article aria-label="모바일 퀘스트 미리보기" className="max-w-[360px] border border-amber-700 bg-black p-5"><b className="text-amber-200">{draft.title||"퀘스트 이름"}</b><p className="mt-2 text-sm">{draft.description}</p><progress className="mt-4 w-full accent-amber-400" max={draft.targetValue} value={Math.min(2,draft.targetValue)}/><p>{Math.min(2,draft.targetValue)} / {draft.targetValue}</p><p className="mt-3 text-sm">{draft.platform.rewards.map(rewardText).join(" + ")}</p></article>}
 </form>
 <section className="space-y-3 border-t border-neutral-800 pt-5"><h3 className="font-black">시즌 관리</h3><div className="flex flex-wrap gap-2">{data?.seasons.map(s=><button key={s.id} className={button} onClick={()=>setSeason({...s,startsAt:localTime(s.startsAt),endsAt:localTime(s.endsAt)})}>{s.name} · {s.status}</button>)}</div><div className="grid gap-3 sm:grid-cols-2"><label>시즌 이름<input className={control} value={season.name} onChange={e=>setSeason({...season,name:e.target.value})}/></label><label>상태<select className={control} value={season.status} onChange={e=>setSeason({...season,status:e.target.value})}>{["ACTIVE","DISABLED","ARCHIVED"].map(s=><option key={s}>{s}</option>)}</select></label><label>시작 (현재 기기 시간)<input className={control} type="datetime-local" value={season.startsAt} onChange={e=>setSeason({...season,startsAt:e.target.value})}/></label><label>종료 (현재 기기 시간)<input className={control} type="datetime-local" value={season.endsAt} onChange={e=>setSeason({...season,endsAt:e.target.value})}/></label></div><button disabled={busy} className={button} onClick={()=>void action(()=>api("/seasons",{...season,id:season.id||undefined,startsAt:new Date(season.startsAt).toISOString(),endsAt:new Date(season.endsAt).toISOString()}))}>시즌 저장</button><button className={button+" ml-2"} onClick={()=>setSeason({id:"",name:"",startsAt:"",endsAt:"",status:"ACTIVE"})}>새 시즌</button></section>
 <section className="space-y-3 border-t border-neutral-800 pt-5"><h3 className="font-black">조건 진단 (진행도·보상 변경 없음)</h3><div className="grid gap-2 sm:grid-cols-3"><select aria-label="테스트 이벤트" className={control} value={test.objectiveType} onChange={e=>setTest({...test,objectiveType:e.target.value})}>{data?.objectives.map(o=><option key={o} value={o}>{labels[o]??o}</option>)}</select><input aria-label="테스트 수량" className={control} type="number" min="1" value={test.amount} onChange={e=>setTest({...test,amount:Number(e.target.value)})}/><select aria-label="테스트 모드" className={control} value={test.mode} onChange={e=>setTest({...test,mode:e.target.value})}>{data?.modes.map(m=><option key={m}>{m}</option>)}</select><select aria-label="테스트 카드 종류" className={control} value={test.cardType} onChange={e=>setTest({...test,cardType:e.target.value})}><option>WRESTLER</option><option>TECHNIQUE</option></select><select aria-label="테스트 등급" className={control} value={test.rarity} onChange={e=>setTest({...test,rarity:e.target.value})}>{["NORMAL","EPIC","LEGENDARY","CHAMPION"].map(r=><option key={r}>{r}</option>)}</select><select aria-label="테스트 결과" className={control} value={test.result} onChange={e=>setTest({...test,result:e.target.value})}><option>WIN</option><option>LOSS</option></select></div><button disabled={busy} className={button} onClick={()=>void action(async()=>{const d=await api<{results:typeof diagnostic}>("/diagnostic",test);setDiagnostic(d.results);})}>테스트 이벤트 실행</button>{diagnostic.map(d=><p key={d.id} className="text-sm">{d.title}: +{d.increment} · {d.reason}</p>)}</section>
 <details><summary>최근 관리자 변경 기록</summary>{data?.audits.map(a=><p key={a.id} className="break-all text-xs text-neutral-400">{new Date(a.createdAt).toLocaleString()} · {a.action} · {a.entityId}</p>)}</details>
 </section>;
}
