import {useEffect,useState} from 'react';
import {cardRecordToDefinition,type PublishedCardRecord} from '@/game/cards/published-cards';
import type {CardDefinition} from '@/game/cards/types';
export function AdminTestDeck({onStart,onClose}:{onStart:(cards:CardDefinition[],decks:[string[],string[]])=>void|Promise<void>;onClose:()=>void}){
 const [cards,setCards]=useState<CardDefinition[]>([]);const [decks,setDecks]=useState<[string[],string[]]>([[],[]]);const [side,setSide]=useState<0|1>(0);const [search,setSearch]=useState('');const [error,setError]=useState('');const [ready,setReady]=useState(false);const [starting,setStarting]=useState(false);
 useEffect(()=>{let live=true;fetch(`${import.meta.env.BASE_URL.replace(/\/$/,'')}/api/admin/cards`,{credentials:'include'}).then(async r=>{if(!r.ok)throw Error();const body=await r.json() as {cards:PublishedCardRecord[]};if(live){setCards(body.cards.map(cardRecordToDefinition));setReady(true);}}).catch(()=>{if(live)setError('카드 목록을 불러오지 못했습니다.');});return()=>{live=false;};},[]);
 const eligible=cards.filter(c=>!c.isToken&&!c.isChampionToken);
 function update(ids:string[]){setDecks(current=>side===0?[ids,current[1]]:[current[0],ids]);}
 return <div role="dialog" aria-modal="true" aria-label="테스트 덱 구성" className="fixed inset-0 z-[250] overflow-y-auto bg-black/95 p-4 text-white"><section className="mx-auto max-w-4xl"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-black">테스트 덱 구성</h2><button onClick={onClose} className="min-h-11 rounded border px-4">닫기</button></div><p className="my-3 text-sm text-neutral-300">중복 제한 없이 최대 60장. 초안·비활성 카드와 주문도 테스트할 수 있습니다. 시작하면 현재 테스트 경기를 새로 시작하며 실제 덱은 저장하지 않습니다.</p><div className="flex flex-wrap gap-2">{([0,1] as const).map(i=><button key={i} aria-pressed={side===i} onClick={()=>setSide(i)} className={`min-h-11 rounded px-3 ${side===i?'bg-amber-400 text-black':'bg-neutral-700'}`}>{i===0?'내 덱':'상대 덱'} ({decks[i].length}장)</button>)}<button onClick={()=>update(eligible.slice(0,25).map(c=>c.id))} disabled={!ready} className="rounded border px-3">빠르게 25장 채우기</button><button onClick={()=>update([])} className="rounded border px-3">선택 덱 비우기</button><button onClick={()=>setDecks(d=>[d[0],[...d[0]]])} className="rounded border px-3">내 덱을 상대 덱에 복사</button></div><input aria-label="테스트 카드 검색" value={search} onChange={e=>setSearch(e.target.value)} placeholder="카드 이름 검색" className="my-4 w-full rounded border border-neutral-600 bg-black p-3"/><div className="mb-4 flex flex-wrap gap-2">{[...new Set(decks[side])].map(id=>{const c=cards.find(c=>c.id===id);return <button key={id} aria-label={`${c?.name} 한 장 빼기`} onClick={()=>{const next=[...decks[side]];next.splice(next.indexOf(id),1);update(next);}} className="rounded bg-neutral-700 p-2">{c?.name} ×{decks[side].filter(x=>x===id).length} −</button>;})}</div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{eligible.filter(c=>c.name.replace(/\s+/gu,'').toLowerCase().includes(search.replace(/\s+/gu,'').toLowerCase())).map(c=><button key={c.id} aria-label={`${c.name} 덱에 추가`} disabled={decks[side].length>=60} onClick={()=>update([...decks[side],c.id])} className="rounded border border-neutral-600 bg-neutral-900 p-3 text-left">{c.imageUrl&&<img src={c.imageUrl} alt="" className="mb-2 h-20 w-full object-cover"/>}<strong>{c.name}</strong><div className="text-xs text-amber-200">{c.cost}골드 · {c.cardType==='TECHNIQUE'?'주문':`${c.attack}/${c.health}`}</div></button>)}</div><p role="status" className="my-3 text-red-300">{error}</p><div className="sticky bottom-0 bg-black py-3"><button disabled={starting||!ready||!decks[0].length||!decks[1].length} onClick={async()=>{setStarting(true);try{await onStart(cards,decks);}catch(e){setError(e instanceof Error?e.message:'테스트를 시작하지 못했습니다.');}finally{setStarting(false);}}} className="min-h-12 w-full rounded bg-amber-400 px-5 font-black text-black">이 덱으로 테스트 시작</button></div></section></div>;
}
