import type { ChampionQuestCondition } from '@workspace/game-engine';
const events = [ ['CARD_PLAYED','카드 사용'], ['CARD_GENERATED','카드 생성'], ['CARD_DRAWN','카드 드로우'], ['CARD_RETIRED','선수 리타이어'], ['CARD_DESTROYED','카드 파괴'], ['ATTACK_DECLARED','공격'], ['DAMAGE_DEALT','피해 발생'], ['CHAMPION_ABILITY_USED','고유 능력 사용'], ['TURN_STARTED','턴 시작'], ['TURN_ENDED','턴 종료'] ];
export function ChampionQuestConditionEditor({value,onChange,depth=0}:{value:ChampionQuestCondition;onChange:(v:ChampionQuestCondition)=>void;depth?:number}) {
  const input='min-h-11 w-full rounded border border-neutral-700 bg-neutral-950 p-2';
  const create=(type:string):ChampionQuestCondition => type==='TURN'?{type,turn:5}:type==='HEALTH'?{type,owner:'SELF',op:'LTE',value:10}:type==='ALL'||type==='ANY'?{type,conditions:[{type:'TURN',turn:5}]}:{type:'EVENT',event:'CARD_PLAYED',owner:'SELF',required:5};
  return <fieldset className="min-w-0 space-y-2 rounded border border-neutral-700 p-3"><label className="block">조건 종류<select className={input} value={value.type} onChange={e=>onChange(create(e.target.value))}><option value="EVENT">행동 누적 횟수</option><option value="TURN">특정 턴 도달</option><option value="HEALTH">챔피언 체력</option>{depth<4&&<><option value="ALL">모든 조건 충족 · AND</option><option value="ANY">하나 이상 충족 · OR</option></>}</select></label>
    {value.type==='TURN'&&<label className="block">전체 턴 번호 이상<input className={input} type="number" min={1} max={999} value={value.turn} onChange={e=>onChange({...value,turn:Number(e.target.value)})}/><span className="text-xs text-neutral-400">선후공의 턴을 각각 셉니다. 5는 전체 5번째 턴입니다.</span></label>}
    {(value.type==='HEALTH'||value.type==='EVENT')&&<label className="block">대상<select className={input} value={value.owner} onChange={e=>onChange({...value,owner:e.target.value as 'SELF'|'ENEMY'})}><option value="SELF">자신</option><option value="ENEMY">상대</option></select></label>}
    {value.type==='HEALTH'&&<><label className="block">비교<select className={input} value={value.op} onChange={e=>onChange({...value,op:e.target.value as typeof value.op})}>{[['LTE','이하'],['LT','미만'],['GTE','이상'],['GT','초과'],['EQ','같음']].map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="block">체력 수치<input className={input} type="number" min={0} max={999} value={value.value} onChange={e=>onChange({...value,value:Number(e.target.value)})}/></label></>}
    {value.type==='EVENT'&&<><label className="block">행동<select className={input} value={value.event} onChange={e=>onChange({...value,event:e.target.value})}>{events.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="block">필요 횟수<input className={input} type="number" min={1} max={999} value={value.required} onChange={e=>onChange({...value,required:Number(e.target.value)})}/></label><label className="block">카드 유형<select className={input} value={value.cardType??''} onChange={e=>{const next={...value};if(e.target.value)next.cardType=e.target.value as 'WRESTLER'|'TECHNIQUE';else delete next.cardType;onChange(next);}}><option value="">모든 유형</option><option value="WRESTLER">선수</option><option value="TECHNIQUE">주문</option></select></label></>}
    {(value.type==='ALL'||value.type==='ANY')&&<>{value.conditions.map((child,index)=><div key={index}><ChampionQuestConditionEditor depth={depth+1} value={child} onChange={next=>onChange({...value,conditions:value.conditions.map((c,i)=>i===index?next:c)})}/><button type="button" disabled={value.conditions.length===1} onClick={()=>onChange({...value,conditions:value.conditions.filter((_,i)=>i!==index)})} className="min-h-11 px-3">조건 제외</button></div>)}<button type="button" disabled={value.conditions.length>=8} onClick={()=>onChange({...value,conditions:[...value.conditions,{type:'TURN',turn:5}]})} className="min-h-11 px-3">조건 추가</button></>}
  </fieldset>;
}
