/** Server batches contain every consecutive event generated by one action. */
export function advanceOnlineEventSequence(lastSequence: number, events: readonly {sequenceNumber:number}[]) {
  let next = lastSequence;
  for (const event of events) {
    if (event.sequenceNumber <= next) continue; // Already accepted/replayed event.
    if (event.sequenceNumber !== next + 1) return {gap:true,lastSequence};
    next = event.sequenceNumber;
  }
  return {gap:false,lastSequence:next};
}
