export const ROUTES = {
  MAIN_MENU: "/",
  SHOP: "/shop",
  PACKS: "/packs",
  COLLECTION: "/collection",
  DECKS: "/decks",
  AI_MATCH: "/ai-match",
  ONLINE: "/online",
  ONLINE_QUICK: "/online/quick",
  ONLINE_FRIENDLY: "/online/friendly",
  ONLINE_MATCH: "/online/match",
  DAILY_QUESTS: "/daily-quests",
  ATTENDANCE: "/attendance",
  ADMIN: "/admin",
} as const;